### ISSUE TITLE
Problem with Tradacons PPRHDR

### ISSUE THREAD

**Issue by a2piazza** [indice-co/EDI.Net#103]
I need to deserialize a Tradacons PPRHDR message like this:

```
STX=ANA:1+5017416000006+8715946000008+180513:025446+11488+       +PPRHDR'
MHD=1+PPRHDR:2'
TYP=2300+ACTUALDET'
SDT=:140276'
CDT=5017416000006'
FIL=6587+1+180512'
MTR=6'
MHD=2+PPRDET:2'
SFR=180513:W:2+A'
PDN=1+:C13T08954010+:001634'
PLO=1+1+:0887'
SFP=1+1+1+T'
SFS=1+1+1+1+STK+2'
PLO=1+2+:1605'
SFP=1+2+1+T'
SFS=1+2+1+1+STK+2'
PLO=1+3+:1610'
SFP=1+3+1+T'
SFS=1+3+1+1+STK+2'
SFS=1+3+1+2+SAL+1'
PLO=1+4+:1611'
SFP=1+4+1+T'
SFS=1+4+1+1+STK+4'
```

I don't understand how to read the PLO's inside each PDN

this is how i tried but without success

```csharp
class PPRHDR
    {
        [EdiValue("X(14)", Path = "STX/1/0")]
        public string SenderCode { get; set; }
        [EdiValue("9(6)", Path = "STX/3/0", Format = "yyMMdd", Description = "TRDT - Date")]
        [EdiValue("9(6)", Path = "STX/3/1", Format = "HHmmss", Description = "TRDT - Time")]
        public DateTime TransmissionStamp { get; set; }
        public PPRHDR_Header Header { get; set; }
        public PPRHDR_Trailer Trailer { get; set; }
        public PPRHDR_Detail Detail { get; set; }
    }


    [EdiMessage, EdiCondition("PPRHDR", Path = "MHD/1")]

    public class PPRHDR_Header
    {
        [EdiValue("9(4)"), EdiPath("TYP")]
        public string TransactionCode { get; set; }
        [EdiValue("9(1)", Path = "MHD/1/1")]
        public int Version { get; set; }
    }

    [EdiMessage, EdiCondition("PPRTLR", Path = "MHD/1")]
    public class PPRHDR_Trailer
    {
        [EdiValue("9(1)", Path = "MHD/1/1")]
        public int Version { get; set; }
    }
    [EdiMessage, EdiCondition("PPRDET", Path = "MHD/1")]
    public class PPRHDR_Detail
    {

        [EdiValue("9(6)", Path = "SFR/0", Format = "yyMMdd", Description = "ReferencePeriod - Date")]
        public DateTime ReferencePeriodDate { get; set; }
        public List<PPRHDR_ProductRows> ProductRows { get; set; }
    }

    [EdiSegmentGroup("PDN")]
    public class PPRHDR_ProductRows
    {
        [EdiValue("9(10)", Path = "PDN/0")]
        public int SequenceNumber { get; set; }
        [EdiValue("X(12)"), EdiPath("PDN/1/1")]
        public string SkuCode { get; set; }
        [EdiValue("X(6)"), EdiPath("PDN/2/1")]
        public string RefCode { get; set; }
        List<PPRHDR_PosRows> PosRows { get; set; }
    }

    [EdiSegment, EdiPath("PLO")]
    public class PPRHDR_PosRows
    {
        [EdiValue("9(10)", Path = "PLO/1")]
        public int SequenceNumber { get; set; }
        [EdiValue("X(12)"), EdiPath("PLO/2/1")]
        public string PosCode { get; set; }
        [EdiValue("9(10)"), EdiPath("SFS/5")]
        public int STK { get; set; }
        [EdiValue("9(10)"), EdiPath("SFS/5")]
        public int SAL { get; set; }

    }
```

Can you help me?
Thanks

Alberto

**Comment by cleftheris** [comment]
@a2piazza Hi can you indicate the desired structure you are aiming for by using spaces? I am not familiar with the PPRHDR transmission and it would help.

Something like this nesting 

```
STX=ANA:1+5017416000006+8715946000008+180513:025446+11488+       +PPRHDR'
    MHD=1+PPRHDR:2'
        TYP=2300+ACTUALDET'
        SDT=:140276'
        CDT=5017416000006'
        FIL=6587+1+180512'
    MTR=6'
    MHD=2+PPRDET:2'
        SFR=180513:W:2+A'
        PDN=1+:C13T08954010+:001634'
        PLO=1+1+:0887'
        SFP=1+1+1+T'
        SFS=1+1+1+1+STK+2'
        PLO=1+2+:1605'
        SFP=1+2+1+T'
        SFS=1+2+1+1+STK+2'
        PLO=1+3+:1610'
        SFP=1+3+1+T'
        SFS=1+3+1+1+STK+2'
        SFS=1+3+1+2+SAL+1'
        PLO=1+4+:1611'
        SFP=1+4+1+T'
        SFS=1+4+1+1+STK+4'
```

**Comment by a2piazza** [comment]
@cleftheris Hi, this is the desidered structure.
 Tank you.

STX=ANA:1+5017416000006+8715946000008+180513:025446+11488+       +PPRHDR'
	MHD=1+PPRHDR:2'
	TYP=2300+ACTUALDET'
	SDT=:140276'
	CDT=5017416000006'
F	IL=6587+1+180512'
	MTR=6'
	MHD=2+PPRDET:2'
		SFR=180513:W:2+A'
			PDN=1+:C13T08954010+:001634'
				PLO=1+1+:0887'
				SFP=1+1+1+T'
				SFS=1+1+1+1+STK+2'
				PLO=1+2+:1605'
				SFP=1+2+1+T'
				SFS=1+2+1+1+STK+2'
				PLO=1+3+:1610'
				SFP=1+3+1+T'
				SFS=1+3+1+1+STK+2'
				SFS=1+3+1+2+SAL+1'
				PLO=1+4+:1611'
				SFP=1+4+1+T'
				SFS=1+4+1+1+STK+4'
				SFC=1+1+T'
				SFX=1+1+1+STK+339'
				SFX=1+1+2+SAL+15'
			PDN=2+:C13T18014020+:016548'
				PLO=2+1+:0013'
				SFP=2+1+1+T'
				SFS=2+1+1+1+STK+3'
				PLO=2+2+:0020'
				SFP=2+2+1+T'
				SFS=2+2+1+1+STK+4'
				PLO=2+3+:0110'
				SFP=2+3+1+T'
				SFS=2+3+1+1+STK+4'
			SFC=1+1+T'
			SFX=1+1+1+STK+339'
			SFX=1+1+2+SAL+15'
		SFL=++71'
		MTR=50496'
	MHD=3+PPRTLR:2'
	PPT=1'
	MTR=3'
END=3'

**Comment by cleftheris** [comment]
Your PDN segment group should either define all its possible members like so

`[EdiSegmentGroup("PDN", "PLO", "SFP", "SFS", "SFC", "SFX")]` 

or define an escape segment, the segment that occurs after the sequence has ended. The second option seems unlikely in your case `[EdiSegmentGroup("PDN", SequenceEnd = "???")]` 

One last note, I take it that in the indented example you provided the SFC and SFX segments after the second PDN are misplaced

If this resolves your issue please close

**Comment by cleftheris** [comment]
On second view of the classes you got.

You should also mark the `PPRHDR_PosRows` class as a segment group too!

So this becomes 
```charp
[EdiSegmentGroup("PDN", "PLO")]
public class PPRHDR_ProductRows


[EdiSegmentGroup("PDN", "PLO")]
public class PPRHDR_ProductRows

.... properties go here


[EdiSegmentGroup("PLO", "SFP", "SFS", "SFC", "SFX")]
public class PPRHDR_PosRows

....
```

**Comment by a2piazza** [comment]
@cleftheris  Hi,
i've modified the class but nothing, still persist PosRows = null

 class PPRHDR
    {
        [EdiValue("X(14)", Path = "STX/1/0")]
        public string SenderCode { get; set; }
        [EdiValue("9(6)", Path = "STX/3/0", Format = "yyMMdd", Description = "TRDT - Date")]
        [EdiValue("9(6)", Path = "STX/3/1", Format = "HHmmss", Description = "TRDT - Time")]
        public DateTime TransmissionStamp { get; set; }
        public PPRHDR_Header Header { get; set; }
        public PPRHDR_Trailer Trailer { get; set; }
        public PPRHDR_Detail Detail { get; set; }
    }


    [EdiMessage, EdiCondition("PPRHDR", Path = "MHD/1")]

    public class PPRHDR_Header
    {
        [EdiValue("9(4)"), EdiPath("TYP")]
        public string TransactionCode { get; set; }
        [EdiValue("9(1)", Path = "MHD/1/1")]
        public int Version { get; set; }
    }

    [EdiMessage, EdiCondition("PPRTLR", Path = "MHD/1")]
    public class PPRHDR_Trailer
    {
        [EdiValue("9(1)", Path = "MHD/1/1")]
        public int Version { get; set; }
    }
    [EdiMessage, EdiCondition("PPRDET", Path = "MHD/1")]
    public class PPRHDR_Detail
    {

        [EdiValue("9(6)", Path = "SFR/0", Format = "yyMMdd", Description = "ReferencePeriod - Date")]
        public DateTime ReferencePeriodDate { get; set; }
        public List<PPRHDR_ProductRows> ProductRows { get; set; }
    }

    [EdiSegmentGroup("PDN", "PLO")]
    public class PPRHDR_ProductRows

    {
        [EdiValue("9(10)", Path = "PDN/0")]
        public int SequenceNumber { get; set; }
        [EdiValue("X(12)"), EdiPath("PDN/1/1")]
        public string SkuCode { get; set; }
        [EdiValue("X(6)"), EdiPath("PDN/2/1")]
        public string RefCode { get; set; }
        List<PPRHDR_PosRows> PosRows { get; set; }
    }

    [EdiSegmentGroup("PLO", "SFP", "SFS", "SFC", "SFX")]
    public class PPRHDR_PosRows
    {
        [EdiValue("9(10)", Path = "PLO/0")]
        public int SequenceNumber { get; set; }
        [EdiValue("X(12)"), EdiPath("PLO/2/1")]
        public string PosCode { get; set; }
        [EdiValue("9(10)"), EdiPath("SFS/5")]
        public int STK { get; set; }
        [EdiValue("9(10)"), EdiPath("SFS/5")]
        public int SAL { get; set; }
    }

**Comment by cleftheris** [comment]
Your property is not public `List<PPRHDR_PosRows> PosRows { get; set; }` thus it is invisible

**Comment by cleftheris** [comment]
Check the tests I added in the commit above

**Comment by a2piazza** [comment]
@cleftheris 
Many many thanks,

This is the complete working class

namespace PPRHDR_to_csv
{
    class PPRHDR
    {
        [EdiValue("X(14)", Path = "STX/1/0")]
        public string SenderCode { get; set; }
        [EdiValue("9(6)", Path = "STX/3/0", Format = "yyMMdd", Description = "TRDT - Date")]
        [EdiValue("9(6)", Path = "STX/3/1", Format = "HHmmss", Description = "TRDT - Time")]
        public DateTime TransmissionStamp { get; set; }
        public PPRHDR_Header Header { get; set; }
        public PPRHDR_Trailer Trailer { get; set; }
        public PPRHDR_Detail Detail { get; set; }
    }


    [EdiMessage, EdiCondition("PPRHDR", Path = "MHD/1")]

    public class PPRHDR_Header
    {
        [EdiValue("9(4)"), EdiPath("TYP")]
        public string TransactionCode { get; set; }
        [EdiValue("9(1)", Path = "MHD/1/1")]
        public int Version { get; set; }
    }

    [EdiMessage, EdiCondition("PPRTLR", Path = "MHD/1")]
    public class PPRHDR_Trailer
    {
        [EdiValue("9(1)", Path = "MHD/1/1")]
        public int Version { get; set; }
    }
    [EdiMessage, EdiCondition("PPRDET", Path = "MHD/1")]
    public class PPRHDR_Detail
    {

        [EdiValue("9(6)", Path = "SFR/0", Format = "yyMMdd", Description = "ReferencePeriod - Date")]
        public DateTime ReferencePeriodDate { get; set; }
        public List<PPRHDR_ProductRows> ProductRows { get; set; }
    }

    [EdiSegmentGroup("PDN", SequenceEnd ="SFX")]
   
    public class PPRHDR_ProductRows

    {
        [EdiValue("9(10)", Path = "PDN/0")]
        public int SequenceNumber { get; set; }
        [EdiValue("X(12)"), EdiPath("PDN/1/1")]
        public string SkuCode { get; set; }
        [EdiValue("X(6)"), EdiPath("PDN/2/1")]
        public string RefCode { get; set; }
       public List<PPRHDR_PosRows> PosRows { get; set; }
    }

    [EdiSegmentGroup("PLO", "SFP", "SFS", "SFC", "SFX")]
    public class PPRHDR_PosRows
    {
        [EdiValue("9(10)", Path = "PLO/0")]
        public int SequenceNumber { get; set; }

        [EdiValue("X(12)"), EdiPath("PLO/2/1")]
        public string PosCode { get; set; }

        [EdiCondition("STK", CheckFor = EdiConditionCheckType.Equal, Path = "SFS/4")]
        public Values STK { get; set; }

        [EdiCondition("SAL", CheckFor = EdiConditionCheckType.Equal, Path = "SFS/4")]
        public Values SAL { get; set; }
    }
    [EdiPath("SFS"), EdiSegment]
    public class Values
    {
        [EdiValue("X(255)", Path = "SFS/3/0")]
        public string SequenceNumber
        {
            get; set;
        }

        [EdiValue("X(3)", Path = "SFS/5/0")]
        public string Value
        {
            get; set;
        }
    }
}

**Comment by cleftheris** [comment]
Glad It worked out!
