### ISSUE TITLE
Serializing: Possible bug with empty paths e.g. Path = "1/1" if no value is present for path "1/0"

### ISSUE THREAD

**Issue by HamiltonManalo** [indice-co/EDI.Net#109]
Hello, 

First, thank you for your work on making this library an effective way to work with EDI. Learning it is difficult and this library has provided a ton of useful information! I hope to offer some contributions as I get more familiar with the project. 

I've been working on an EDI Serialization model DESADV D96A UNOC3 and with this set of values 

```csharp
            [EdiValue("X(3)", Path = "PAC/0/0")]
            public string PackageCount { get; set; }

            [EdiElement, EdiValue("X(3)", Path = "PAC/1/1")]
            public string PackageDetailLevel { get; set; }

            [EdiValue("X(3)", Path = "PAC/2/0")]
            public string PackageType { get; set; }
```
with the following values assigned
```
            PackageCount = "1",
            PackageDetailLevel = "52",
            PackageType = "PK"
```
Its meant to produce an element with the following values 

> PAC+1+:52+PK'

However when serialized it produces 

> PAC+1+::52+PK'

I've tried adjusting the path values to "1/2" which will produce  
>PAC+1+:::52+PK'

which is an additional value and "1/0" produces an expected 
>PAC+1+52+PK'

**Comment by cleftheris** [comment]
Hi I am currently in vacations so I will try to find some time to check this out but it may take a while.

**Comment by HamiltonManalo** [comment]
cleftheris, 

Enjoy your vacation and thank you for your response. I believe I'll be able to create a workaround for it in the mean time.

**Comment by cleftheris** [comment]
Hi again, 

I think the `EdiElement` attribute is misplaced. It should not be present on a property representing a component. Components are considered the only containers of values. So even if there is a sole value inside an element there is an implicit component there holding the value. The extra EdiElement attribute present on `PackageDetailLevel` seems to be confusing the serializer. Try to remove it and report back.

I think that I should create an improvement that either breaks with exception when there is a misconfiguration or ignores the element attribute when a value attribute is present.

**Comment by HamiltonManalo** [comment]
Hello,

Thank you for getting back to me regarding the issue. 

I did a couple of tests and found that removing the EdiElement did not resolve the issue, I toyed around with the attributes to no avail. Here is the current full class. Thank you again. 

```
    [EdiSegment]
    public class PACSegment
    {
        [EdiValue("X(3)", Path = "PAC/0")]
        public string PackageCount { get; set; }
        
        [EdiPath("PAC/1/1"), EdiValue("X(3)")]
        public string PackageDetailLevel { get; set; }

        [EdiValue("X(3)", Path = "PAC/2/0")]
        public string PackageType { get; set; }
    }
```

**Comment by cleftheris** [comment]
Release coming up today v1.8
