### ISSUE TITLE
Count controls and segments?

### ISSUE THREAD

**Issue by User13377** [indice-co/EDI.Net#113]
Hi!

First of all, what a great library you have created for reading and creating D96A format invoices.

I only have one issue using this library and that is, how do I count the segments/controls?

Meaning, is there any solution to be able to fill the EDIfact01.cs class properties:
TrailerMessageSegmentsCount
TrailerControlCount

Do I have to manually count the segments and controls myself and assign or is there something that does this for me?

Thanks

**Comment by cleftheris** [comment]
Hi @User13377 unfortunately the library does not do much about it at the moment. Although this is rather easy to implement. See issue #17 where I am writing about autogenerated values. 

I will see if I can find some time to check it out.

**Comment by User13377** [comment]
@cleftheris Thanks for a quick reply!

I will look into it.

Thanks

**Comment by GVG** [comment]
Hello all! Any progress on this?

**Comment by cleftheris** [comment]
@GVG I am working on a solution for this but is going pretty slow. I am currently overwhelmed with other work. I hope to come back to this soon. Follow issue #17 for updates

**Comment by GVG** [comment]
@cleftheris thank you for the response. Segment counting is crucial feature in my current project :/

**Comment by bugproof** [comment]
@GVC did you implement it? I'm currently implementing segment counting myself.

**Comment by GVG** [comment]
@bugproof currently I'm using this crutch:
```csharp
private static readonly byte[] _unt = Encoding.UTF8.GetBytes("UNT+000000+");
private static readonly byte[] _segmentSeparator = Encoding.UTF8.GetBytes("'\r\n");

public static void CountAndSetUNT(byte[] edi)
{
    var untIndex = edi.IndexOf(_unt, edi.Length > 200 ? edi.Length - 200 : 0);
    var segments = -3;
    var index = 0;

    while (index != -1)
    {
        index = edi.IndexOf(_segmentSeparator, index + 1, untIndex);
        segments++;
    }

    var segmentsBytes = Encoding.UTF8.GetBytes(segments.ToString());

    for (var i = 0; i < segmentsBytes.Length; i++)
        edi[untIndex + 8 + i] = segmentsBytes[i];
}
```
`edi.IndexOf()` is my extension method which finds index of UNT segment in byte array by given sequence of bytes.
A dirty ~~permanent~~ temporary solution, but works fine.

**Comment by bugproof** [comment]
@GVG ah so you're counting it after it's already serialized. I was thinking to count it before serialization with some method

**Comment by GVG** [comment]
@bugproof yes. This was primitive and bulletproof solution. Counting them during serialization would take much more time to implement.

**Comment by bugproof** [comment]
@GVG a bit ugly and using reflection and recursion, yours is probably better as long as it supports multiple messages:

You pass message type to it (class marked with `[EdiMessage]`)

```cs
private int CountSegments(Type type)
{
    static bool IsSegment(MemberInfo type) => Attribute.IsDefined(type, typeof(EdiSegmentAttribute));
    static bool IsSegmentGroup(MemberInfo type) => Attribute.IsDefined(type, typeof(EdiSegmentGroupAttribute));

    var segmentCount = 0;

    foreach (var property in type.GetProperties())
    {
        var propertyType = property.PropertyType;
        if (propertyType.IsGenericType && typeof(ICollection).IsAssignableFrom(propertyType))
        {
            var itemType = propertyType.GetGenericArguments()[0];
            if (IsSegment(itemType))
            {
                var collection = (ICollection)property.GetValue(this);
                segmentCount += collection?.Count ?? 0;
            }
            else if (IsSegmentGroup(itemType))
            {
                segmentCount += CountSegments(itemType);
            }
        }
        else if (IsSegment(propertyType))
        {
            segmentCount++;
        }
        else if (IsSegmentGroup(propertyType))
        {
            segmentCount += CountSegments(propertyType);
        }
    }

    return segmentCount;
}
```

**Comment by GingerNinjaa** [comment]
Hi,

This is implemented in the library ?

**Comment by cleftheris** [comment]
There is an internal counter inside the Serializer but I have not had the time to check where the actual need is accross the spectrum of EDI so that I can introduce an extension on the `EdiValueAttribute`. If the above code is the case I may  Messages keep segment counts, Groups keep message counts and Interchange trailers keep Groups or message counts then I could work it out. I just was not sure that this is the case for X12 and Trandacoms. 

If someone has the curiosity to try it out the global counter internally is `EdiWriter.SegmentCount` &  `EdiReader.SegmentCount` for validation respectively.

**Comment by GingerNinjaa** [comment]
**EdiWriter.SegmentCount** & **EdiReader.SegmentCount** always  give me "1"

**Comment by cleftheris** [comment]
Hi guys I will put out an updated version soon with control counts implemented at least for the well known structures Message Group and Interchange (segment count, message count, group count). Related to #17
