### ISSUE TITLE
Easy way to count segment

### ISSUE THREAD

**Issue by roberttor** [indice-co/EDI.Net#119]
Hello all,

First, many thanks for sharing your code!!!

I need to send the edifact DESADV message to a customent and I'm trying to use your libraries. I create the edi message from a POCO class.
All is working as expected except for the UNT segment, where I should fill the total number of segments for the message..

I have the option of mannually increment a counter every time that I create a new segment when I fill the POCO class but I think that it's not a good/elegant solution. 

Any help/idea would be very appreciated.

Thank you,

Robert

Sorry, I've seen now that there is a previous issue/enhacement related to my doubt. I've checked it but there is no answer/solution.

**Comment by cleftheris** [comment]
Hi @roberttor and thank you for your interest in Edi.Net. 
There is already an issue regarding the segment count #113 so please switch the discussion there. I have a draft of the feature but it is unfinished. I will try to see where I have left it in the following days and maybe publish a prerelease package for you to test. 

Also If you feel like adding your models along with a test to the tests project feel free to make a pull request.

C.

**Comment by cleftheris** [comment]
related to #17
