### ISSUE TITLE
EdiSegment with list of EdiElement

### ISSUE THREAD

**Issue by dinmukhamed09** [indice-co/EDI.Net#121]
Hi,

I have issue with Segment exist list of values.

Example:
```
ATR+NEW+PRIO:N'
ATR+NEW+TGIC:465+TGNO:716073+TGPC:SVX'
ATR+NEW+ACCS:A+BGCL:Y+BRDP:KBP+OFFP:TSE+PRIL:N'
```

I want get List of values like:

```csharp
[EdiSegment, EdiPath("ATR")]
public class Main
{
     List<Information> Informations { get; set; }
}
```
Attention edivalue exist n counter
```csharp
public class Information
{
    [EdiValue("X(4)", Path = "ATR/n/0")]
    public string Code{ get; set; }

    [EdiValue("X(256)", Path = "ATR/n/1")]
    public string Value{ get; set; }
}
```
1st Main:
    Information[0].Code = PRIO

2nd Main:
    Information[0].Code = TGIC
    Information[0].Code = TGNO
    Information[0].Code = TGPC

3rd Main:
    Information[0].Code = ACCS
    Information[0].Code = BGCL
    Information[0].Code = BRDP
    Information[0].Code = PRIL

**Comment by cleftheris** [comment]
If I understand this correctly you need to bind a repeating Element to a list of elements.

This feature is not supported yet. As a workaround you can make multiple subclass of Information or multiple properties of `Code` and `Value` inside the `Main` class (ATR). 

```csharp
[EdiSegment, EdiPath("ATR")]
public class Main
{
     [EdiElement, EdiPath("ATR/0")]
     Information Information { get; set; }
     [EdiElement, EdiPath("ATR/1")]
     Information1 Information1 { get; set; }
     [EdiElement, EdiPath("ATR/2")]
     Information2 Information2 { get; set; }
}
public class Information
{
    [EdiValue("X(4)", Path = "ATR/0/0")]
    public virtual string Code{ get; set; }

    [EdiValue("X(256)", Path = "ATR/0/1")]
    public virtual string Value { get; set; }
}
public class Information1 : Information
{
    [EdiValue("X(4)", Path = "ATR/1/0")]
    public virtual string Code{ get; set; }

    [EdiValue("X(256)", Path = "ATR/1/1")]
    public virtual string Value { get; set; }
}
public class Information2 : Information
{
    [EdiValue("X(4)", Path = "ATR/2/0")]
    public virtual string Code{ get; set; }

    [EdiValue("X(256)", Path = "ATR/2/1")]
    public virtual string Value { get; set; }
}
```

Related to #105

**Comment by cleftheris** [comment]
Checkout this example https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/Models/EdiFact_Issue121_ElementList.cs

and I will be posting a beta release 1.9 soon

**Comment by dinmukhamed09** [comment]
Hi,

Thank you works good. When you release new version?

**Comment by cleftheris** [comment]
Just published 1.9 to nuget

**Comment by dinmukhamed09** [comment]
I used in project. And have problem.

ATR+NEW+BRDC:J+BRDS;B+BRDT:S+BRDY:DGR

[EdiSegment, EdiPath( "ATR")]
public class Main
{
[EdiPath("ATR/*")]
public List<Information> Informations { get; set; }
    }

    [EdiElement]
    public class Information
    {
        [EdiValue("X(4)", Path = "*/*/0")]
        public string Code { get; set; }

        [EdiValue("X(4)", Path = "*/*/1")]
        public string Value{ get; set; }
    }

I Have error.
First item can't get. And the latest not show and some values is incorrect.
I think because, first element doesn't exist a value

**Comment by cleftheris** [comment]
You have to give me a complete sample and a model. Because for this transmission the feature works as expected and binds everything.
```
UNB+UNOD'
UNH+000001'
ATR+NEW+PRIO:N'
ATR+NEW+TGIC:465+TGNO:716073+TGPC:SVX'
ATR+NEW+ACCS:A+BGCL:Y+BRDP:KBP+OFFP:TSE+PRIL:N'
UNT+3'
UNZ+1'
```
Here is the test
https://github.com/indice-co/EDI.Net/blob/ff3d9ee2dc32b93ac801de4fee0304a424257da6/test/indice.Edi.Tests/EdiTextReaderTests.cs#L923

**Comment by dinmukhamed09** [comment]
I saw. Try use that.

 public class EdiFact_Issue121_ElementList
    {
        public Message Msg { get; set; }

        [EdiMessage]
        public class Message
        {
            [EdiCondition("NEW", CheckFor = EdiConditionCheckType.Equal, Path = "ATR/0/0")]
            public List<Attribute> Attributes { get; set; }

            [EdiCondition("V", CheckFor = EdiConditionCheckType.Equal, Path = "ATR/1/0")]
            public List<Criteria> Attributes1 { get; set; }
        }

        [EdiSegment, EdiPath("ATR")]
        public class Attribute
        {
            [EdiPath("ATR/*")]
            public List<Information> Infos { get; set; }
        }

        [EdiElement]
        public class Information
        {
            [EdiValue("X(4)", Path = "*/*/0")]
            public string Code { get; set; }

            [EdiValue("X(256)", Path = "*/*/1")]
            public string Value { get; set; }
        }

        [EdiSegmentGroup("ATR")]
        public class Criteria
        {
            [EdiValue("X(100)", Path = "LTS/0", Mandatory = true)]
            public string Value { get; set; }
        }
    }

UNB+UNOD'
UNH+000001'
ATR+NEW+PRIO:N'
ATR+NEW+TGIC:465+TGNO:716073+TGPC:SVX'
ATR+NEW+ACCS:A+BGCL:Y+BRDP:KBP+OFFP:TSE+PRIL:N'
ATR++V'
LTS+2'
UNT+3'
UNZ+1'

**Comment by cleftheris** [comment]
@dinmukhamed09 I have revisited the case and finally figured this out!! Now the deserializer can work even the last case! check the Test here

**Comment by cleftheris** [comment]
I will post a new version v1.9.4
