### ISSUE TITLE
Editelement - Editpath Problem

### ISSUE THREAD

**Issue by nawasdk** [indice-co/EDI.Net#124]
Hello there,

first of all, thank you for the great libary. 
The task i'm up to, is to get amazon orders and the customer can decide, whether they accept the order and send their stuff to amazon or decline it,. 
In the amazon example file and description is an area, called PIA (additional product id) which is used, to specify additional or substitutional item identification  codes.
To get the PIA, i created the PIA Class and extended the edisegment LineItem. 

This is what the Line Item looks like with the PIA line
```
LIN+3'
PIA+5+3899408268X-39:SA'
QTY+21:3'
PRI+AAA:3.85'
```

And this is what my PIA Class looks like:
```vbnet

    <EdiElement, EdiPath("PIA/1")>
    Public Class ProductID
        <EdiValue("X(3)", Path:="PIA/1/2")>
        Public Property ProdID As String
        <EdiValue("X(35)", Path:="PIA/1/0")>
        Public Property ItemNumber As String
        <EdiValue("X(3)", Path:="PIA/1/1")>
        Public Property ItemNumberCOde As String
        <EdiValue("X(3)", Path:="PIA/1/2")>
        Public Property ItemNumberIdentification As String
    End Class`
```
This is the LineItem Class:

  ```vbnet
    <EdiSegment, EdiSegmentGroup("LIN", SequenceEnd:="UNS")>
    Public Class LineItem
        <EdiValue("X(1)", Path:="LIN/0/0")>
        Public Property LineNumber As Integer
        <EdiValue("9(3)", Path:="LIN/1/0")>
        Public Property Code As String
        Public Property NumberIdentification As ItemNumber
        Public Property Period As Period
        Public Property Prices As List(Of PriceDetails)
        Public Property Quantity As Quantity
        Public Property ProductID As ProductID
    End Class
```

The important part was to get the additional itemnumber and after some trial and error, i got this task solved.  But i'm unable to set the right EditPath to get the '5' from the PIA Line (PIA+**5**+3899408268X-39:SA). 
I don't get the concept of the EditPath and i don't know why and what is, i'm doing wrong (besides the obvious reason that i'm a vb programmer).

Thanks in advance
Tim

**Comment by cleftheris** [comment]
Hi you will need one separate class for each segment PIA (ProductID), LIN (LineItem),  QTY(Quantity), and PRI (dont know what this is). And then you will need a separate Line class that inherits from LineItem to group them all that will be `<EdiSegmentGroup("LIN","PIA","QTY","PRI")>` . You will **remove the segment group from the LineItem**.

The group will look like this:
```vbnet
  <EdiSegmentGroup("LIN","PIA","QTY","PRI")>
  Public Class Line inherits LineItem
      Public Property PIA As ProductID
      Public Property QTY As Quantity
      Public Property PRI As PRIClass
  End Class
```
I hope this helps

**Comment by nawasdk** [comment]
Hi,thank you for your fast reply, i will try the suggested changes during the day.  
The PRI Class contains the price information for the item.

**Comment by nawasdk** [comment]
I tried your solution, but nothing changed for me. maybe i wasn't describing my problem well enough. 
I got all the values (quantity, prices, PIA) for the product that i wanted stored in my object, except

**Comment by nawasdk** [comment]
Hello, unfortunately the issue isn't just fixed by following your instructions. I've got the exact same results beforehand. I get the correct value for the Itemnumber  (3899408268X-39) and the correct value for the itemnumbercode ('SA'). The value i'm missing is itemnumberidentification
PIA+**5**+3899408268X-39:SA'
(in my EDI FIle it's the value '5') and i don't now what i'm missing or doing wrong in my Class. 
![edi](https://user-images.githubusercontent.com/48097520/53640162-be91d780-3c2b-11e9-9a16-4825f344bf3a.PNG)

I think the problem is that the editpath property of the ItemNumberIdentification property is wrong but i don't know the right path value  (i think it should be  <EdiValue("X(3)", Path:="PIA/0/0")>   but maybe i have a total misunderstanding of the path property)

thanks again
Tim

p.s.: sorry for closing and reopening the issue - i missclicked.

**Comment by cleftheris** [comment]
Now that I look more closely I think you are correct. You have the paths wrong on the ItemNumberIdentification, but also if you have to bind this all togather **you need PIA decorated with a segment attribute**. It seems that you got the same paths on two properties.

This should be like.

```vbnet
    <EdiSegment, EdiPath("PIA")>
    Public Class ProductID
        <EdiValue("X(3)", Path:="PIA/1/2")>
        Public Property ProdID As String
        <EdiValue("X(35)", Path:="PIA/1/0")>
        Public Property ItemNumber As String
        <EdiValue("X(3)", Path:="PIA/1/1")>
        Public Property ItemNumberCOde As String
        <EdiValue("X(3)", Path:="PIA/0/0")>
        Public Property ItemNumberIdentification As String
    End Class
```

**Comment by nawasdk** [comment]
Thank you very much, this solved the issue. Have a nice week and thanks for the support.
