### ISSUE TITLE
Errors exist after running preLaunchTask 'build'

### ISSUE THREAD

**Issue by sonisudarshan0** [indice-co/EDI.Net#128]
**Program.cs(35,43): error CS0246: The type or namespace name 'Interchange_Issue95' could not be found (are you missing a using directive or
an assembly reference?) [D:\Projects\Projects.csproj]
Program.cs(36,37): error CS0103: The name 'Helpers' does not exist in the current context [D:\Projects\Projects.csproj]
Program.cs(38,63): error CS0246: The type or namespace name 'Interchange_Issue95' could not be found (are you missing a using directive or
an assembly reference?) [D:\Projects\Projects.csproj]
Program.cs(40,10): error CS0103: The name 'Assert' does not exist in the current context [D:\Projects\Projects.csproj]
CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point [D:\Projects\Projects.csproj]**

![error_edi_test2](https://user-images.githubusercontent.com/50704950/57999764-31587380-7af4-11e9-80fb-6cca9db9c40c.png)

**Comment by cleftheris** [comment]
Please do not post issues that are not in the scope of the library. This is related to debuggin an xutit test library. Use stakoverflow instead.

Thanks.
