### ISSUE TITLE
Add Support for Repeating multi-line Segements in EDI messages

### ISSUE THREAD

**Issue by cwhellams** [indice-co/EDI.Net#13]
Currently EDI.net has support for the concept of repeating segments which can be parsed into a strongly-typed collection type such as a List<myType>. This is supported by making a POCO with the EdiSegment attribute and then adding an EdiPath attribute to identify the segment in the file.

The proposal is to extend this feature to support a multi-line segment i.e. a segment that may span multiple lines in the file.

An example of this could be a time series which repeats n times. It is assumed that the repeating segment is sequentially repeating i.e. there are no other values , segments etc intermingled with the repeating segment. 

The repeating segment will always have an identifier for the start of the segment and may or may not have a terminator. If there is no terminator then it is assumed the next instance of the identifier found in the file indicates that beginning of a new segment in the series.

 example data : time series identified with "LIN" with no terminator, can repeat "n" times.

LIN+1++1420:::SM'
DTM+324:201010192300201010192400:Z13'
PRI+CAL:-2100'
RNG+4+Z01:-0.1'
PRI+CAL:21000'
RNG+4+Z01:-0.1'

LIN+2++1420:::SM'
DTM+324:201010200000201010200100:Z13'
PRI+CAL:-2100'
RNG+4+Z01:0'
PRI+CAL:21000'
RNG+4+Z01:0'

LIN+3++1420:::SM'
DTM+324:201010200100201010200200:Z13'
PRI+CAL:-2100'
RNG+4+Z01:0'
PRI+CAL:21000'
RNG+4+Z01:0'

LIN+4++1420:::SM'
DTM+324:201010200200201010200300:Z13'
PRI+CAL:-2100'RNG+4+Z01:0'
PRI+CAL:21000'
RNG+4+Z01:0'

**Comment by cleftheris** [comment]
@cwhellams this seems like a good idea. I am currently out for vacations but I will look into this when I am back.

**Comment by cleftheris** [comment]
Hi @cwhellams I am back :)

I have started looking for similar behavior in existing serializers. I would say that this seams more like a transformation to me. For example in xml when someone needs to create a nested structure form a flattened one, one would make use of xslt "foreach" like in this [SO article here](http://stackoverflow.com/questions/14791434/xslt-transformation-from-flat-structure-to-nested). 

I am thinking of introducing a new attribute for this so I am looking for inspiration on how to name the thing as well as what kinds of functionality and additional properties (settings) would it need to expose.

On the implementation side of things this seems to be relatively easy to implement. I am looking on enhancing the `TryCreateContainer` method call on `EdiSerializer` with an additional case similar to how  `FindForCurrentLogicalStructure` works. This could possibly mean introducing a new option in the EdiStructureType enumeration. I am still thinking about this and could be wrong.

I will come back with an update when I have a suggestion. In the meantime any thoughts are welcome.

**Comment by cwhellams** [comment]
Hi @cleftheris 

You could look at FileHelpers Master-Detail records - its not quite the same but that library is very flexible and can support many custom file formats http://www.filehelpers.net/

**Comment by cleftheris** [comment]
@cwhellams Final implementation works with a new attribute called `[SegmentGroup]`. check this out https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/Models/EdiFact01.cs#L149

**Comment by cleftheris** [comment]
Check a sample implementation for the Period DTM (`DTMPeriod`) https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/Models/EdiFact01.cs#L12

**Comment by cleftheris** [comment]
Multi line segments should support nesting. This has surfaced while investigating this sample. A fix is on the way
