### ISSUE TITLE
Parsing optional seconds and milliseconds

### ISSUE THREAD

**Issue by prajaybasu** [indice-co/EDI.Net#130]
Is there any way to parse optional seconds/milliseconds as DateTime?
For example, in the X12 4010 204 standard, G62/04 is expressed like this: 

> Time expressed in 24-hour clock time as follows: HHMM, or HHMMSS, or HHMMSSD, or
HHMMSSDD, where H = hours (00-23), M = minutes (00-59), S = integer seconds (00-59) and
DD = decimal seconds; decimal seconds are expressed as follows: D = tenths (0-9) and DD =
hundredths (00-99)

Trying to use the picture`9(8)` with the format `HHmmssff` results in 00:00 and not the expected time (HH:mm:00.00) when the EDI only has HHmm data.

**Comment by cleftheris** [comment]
Hi I am looking into this and as far as I can tel this should not be rendom. Each date and time component seems to have a fixed format and it is respected. What I am saying is that is should consistently either be transmitting HHMMSS or HHMMSSD or HHMMSSDD. Please let me know am I missing something.

In the meantime I am investigating a non breaking change that may allow the fraction of a seccond part and only that to be optional. Is this what you are aiming for?

**Comment by cleftheris** [comment]
I pushed a fix for this. Expect it to land in the day in `v1.9.1`

**Comment by prajaybasu** [comment]
> Hi I am looking into this and as far as I can tel this should not be rendom. Each date and time component seems to have a fixed format and it is respected. What I am saying is that is should consistently either be transmitting HHMMSS or HHMMSSD or HHMMSSDD. Please let me know am I missing something.
> 
> In the meantime I am investigating a non breaking change that may allow the fraction of a seccond part and only that to be optional. Is this what you are aiming for?

I understand that a vendor will consistently transmit in a fixed format but I think it would be nice to be able to share code for multiple vendors that might have different time formats to be future proofing.  So I am looking for a solution where  DateTime will still parse seconds and decimal seconds for vendors that use them while still being able to correctly parse HHMM (currently it will read the value as 00:00).

**Comment by cleftheris** [comment]
Understood,

Thanks for your feedback. check out v1.9.1 on nuget it is more forgiving for the time parsing. https://www.nuget.org/packages/indice.Edi/1.9.1
