### ISSUE TITLE
X12 850 DTM 

### ISSUE THREAD

**Issue by muazg** [indice-co/EDI.Net#135]
Hi ,

When I deserialize the x12 850 file to  PurchaseOrder850 object,  
AvailableFromDate , ArrivalDate values  were not created. Is there any problem with the deserialization of? If you want I can share the edi file

**Comment by cleftheris** [comment]
Please add a sample transmission in order to show case what you have tried and what you are expecting as a result.

Thanks.

**Comment by muazg** [comment]
Thank you for your answer and help. The contents of the transmission file are as follows.




ISA*00*          *00*          *01*049351117      *ZZ*TEST         *190807*0842*U*00401*000000002*0*T*>~GS*PO*049351117*TEST*20190807*0842*2*X*004010~ST*850*0003~BEG*05*CP*740150**20191001~PER*BD*0~TD5*O***O~N1*VN*CDT~PO1*10*13200*SF***ST*F07EXPLBA1818~CUR*BY*USD~PID*F****EXPLORERBARCELONA18X18~PO4**6055.05*PC~REF*19*CADC1~REF*ZZ*LAX~DTM*002*20190309~DTM*038*20190309~PO1*20*13892*SF***ST*F07EXPLLO1224~CUR*BY*USD~PID*F****EXPLORERLONDON12X24~PO4**7168.21*PC~REF*19*CADC1~REF*ZZ*LAX~DTM*002*20190309~DTM*038*20190309~PO1*30*13892*SF***ST*F07EXPLLO1224~CUR*BY*USD~PID*F****EXPLORERLONDON12X24~PO4**7168.21*PC~REF*19*CADC1~REF*ZZ*LAX~DTM*002*20190309~DTM*038*20190309~PO1*40*13237*SF***ST*F19POCOOA0636P9~CUR*BY*USD~PID*F****POCONOOAK6X36~PO4**9091.35*PC~REF*19*CADC1~REF*ZZ*LAX~DTM*002*20190309~DTM*038*20190309~PO1*50*13430*SF***ST*F19POCOSM0624P14~CUR*BY*USD~PID*F****POCONOSMOKE6X24~PO4**13859.65*PC~REF*19*CADC1~REF*ZZ*LAX~DTM*002*20190309~DTM*038*20190309~PO1*60*13237*SF***ST*F19POCOSM0636P9~CUR*BY*USD~PID*F****POCONOSMOKE6X36~PO4**9091.35*PC~REF*19*CADC1~REF*ZZ*LAX~DTM*002*20190309~DTM*038*20190309~PO1*100*6000*SF***ST*F07EXPLBA1818~CUR*BY*USD~PID*F****EXPLORERBARCELONA18X18~PO4**2752.29*PC~REF*19*CADC1~REF*ZZ*LAX~DTM*002*20190517~DTM*038*20190517~PO1*70*13237*SF***ST*F19POCOSM0636P9~CUR*BY*USD~PID*F****POCONOSMOKE6X36~PO4**9091.35*PC~REF*19*CADC1~REF*ZZ*LAX~DTM*002*20190309~DTM*038*20190309~PO1*80*13237*SF***ST*F19POCOOA0636P9~CUR*BY*USD~PID*F****POCONOOAK6X36~PO4**9091.35*PC~REF*19*CADC1~REF*ZZ*LAX~DTM*002*20190317~DTM*038*20190317~PO1*90*13237*SF***ST*F19POCOSM0636P9~CUR*BY*USD~PID*F****POCONOSMOKE6X36~PO4**9091.35*PC~REF*19*CADC1~REF*ZZ*LAX~DTM*002*20190317~DTM*038*20190317~CTT*10~SE*87*0003~ST*850*0004~BEG*05*CP*740151**20191101~PER*BD*0~TD5*O***O~N1*VN*CDT~PO1*10*13200*SF***ST*F07EXPLBA1818~CUR*BY*USD~PID*F****EXPLORERBARCELONA18X18~PO4**6055.05*PC~REF*19*FLDC1~REF*ZZ*MIA~DTM*002*20190312~DTM*038*20190312~PO1*20*13892*SF***ST*F07EXPLLO1224~CUR*BY*USD~PID*F****EXPLORERLONDON12X24~PO4**7168.21*PC~REF*19*FLDC1~REF*ZZ*MIA~DTM*002*20190312~DTM*038*20190312~PO1*30*13892*SF***ST*F07EXPLLO1224~CUR*BY*USD~PID*F****EXPLORERLONDON12X24~PO4**7168.21*PC~REF*19*FLDC1~REF*ZZ*MIA~DTM*002*20190312~DTM*038*20190312~PO1*40*13892*SF***ST*F07EXPLLO1224~CUR*BY*USD~PID*F****EXPLORERLONDON12X24~PO4**7168.21*PC~REF*19*FLDC1~REF*ZZ*MIA~DTM*002*20190312~DTM*038*20190312~PO1*50*13892*SF***ST*F07EXPLMI1224~CUR*BY*USD~PID*F****EXPLORERMILAN12X24~PO4**7168.21*PC~REF*19*FLDC1~REF*ZZ*MIA~DTM*002*20190312~DTM*038*20190312~PO1*110*13430*SF***ST*F19POCOSM0624P14~CUR*BY*USD~PID*F****POCONOSMOKE6X24~PO4**13859.65*PC~REF*19*FLDC1~REF*ZZ*MIA~DTM*002*20190326~DTM*038*20190326~PO1*60*13892*SF***ST*F07EXPLMI1224~CUR*BY*USD~PID*F****EXPLORERMILAN12X24~PO4**7168.21*PC~REF*19*FLDC1~REF*ZZ*MIA~DTM*002*20190312~DTM*038*20190312~PO1*70*13430*SF***ST*F19POCOSM0624P14~CUR*BY*USD~PID*F****POCONOSMOKE6X24~PO4**13859.65*PC~REF*19*FLDC1~REF*ZZ*MIA~DTM*002*20190312~DTM*038*20190312~PO1*80*13430*SF***ST*F19POCOSM0624P14~CUR*BY*USD~PID*F****POCONOSMOKE6X24~PO4**13859.65*PC~REF*19*FLDC1~REF*ZZ*MIA~DTM*002*20190312~DTM*038*20190312~PO1*90*13430*SF***ST*F19POCOSM0624P14~CUR*BY*USD~PID*F****POCONOSMOKE6X24~PO4**13859.65*PC~REF*19*FLDC1~REF*ZZ*MIA~DTM*002*20190312~DTM*038*20190312~PO1*100*13430*SF***ST*F19POCOSM0624P14~CUR*BY*USD~PID*F****POCONOSMOKE6X24~PO4**13859.65*PC~REF*19*FLDC1~REF*ZZ*MIA~DTM*002*20190312~DTM*038*20190312~CTT*11~SE*95*0004~GE*2*2~IEA*1*000000002~

**Comment by muazg** [comment]
Hi Mr. Cleftheris ,

The transmission file is attached. When I try to deserialize the transmission file, AvailableFromDate and ArrivalDate fields values are null.  The Type of these values are DTM.

If you can check it, I would be grateful.

Best Regards.

[TransmissionFile.txt](https://github.com/indice-co/EDI.Net/files/3514471/TransmissionFile.txt)

**Comment by cleftheris** [comment]
Hi I am currently on vacations I will check it out hopefully next week

**Comment by cleftheris** [comment]
Hi again,

after checking out your transmission I realized that your vendor is sending DTM codes `002` and `038` in each OrderDetail Item. These stand for `DeliveryRequested` and `ShipNoLater` dates. You have to realize that there are variations of each transmission type and sometimes it is not unusual to see slight differences from vendor 2 vendor implementations.

That said the sample model you are using (the one from the test project) makes use of two other DTM codes (`018` and `067` respectively) which stand for `Availablefrom` and `Arrival` dates. 

In order to map the ones you are actualy recieving in the transmission you got to add two more properties in the model class under the AvailableFromDate and ArrivalDate.

```csharp

            [EdiCondition("018", Path = "DTM/0/0")]
            public DTM AvailableFromDate { get; set; }

            [EdiCondition("067", Path = "DTM/0/0")]
            public DTM ArrivalDate  { get; set; }

            [EdiCondition("002", Path = "DTM/0/0")]
            public DTM DeliveryRequestedDate { get; set; }

            [EdiCondition("038", Path = "DTM/0/0")]
            public DTM ShipNoLaterDate { get; set; }
```

Notice the condition attribute. This limits the DTM segment to be bound to the property according the the condition found on the first component.

For complete reference check the full list here http://ecomgx17.ecomtoday.com/edi/EDI_4010/el374.htm
