### ISSUE TITLE
[Q] Serializing : Do not write segment if no value is not available

### ISSUE THREAD

**Issue by FannyMaulny** [indice-co/EDI.Net#139]
Hello,

Is it possible not to write an empty segment when serializing?
My EDIFACT structure is :
![image](https://user-images.githubusercontent.com/56251767/66463803-1a53f700-ea7e-11e9-88d2-59c259da9a4c.png)
I have a group of NAD segments followed by RFF segments where the RFF segment is optional.

Here is my code : 
[EdiSegments.txt](https://github.com/indice-co/EDI.Net/files/3706274/EdiSegments.txt)
[EdiPaiement.txt](https://github.com/indice-co/EDI.Net/files/3706275/EdiPaiement.txt)
[Program.txt](https://github.com/indice-co/EDI.Net/files/3706276/Program.txt)

And when I serialize my object to generate my EDI file (function Test3 ()), I get this : 
![Exemple Test3 edi](https://user-images.githubusercontent.com/56251767/66464502-6f443d00-ea7f-11e9-9adc-c66408de442a.png)

I do not want the empty RFF segment that follows the NAD + DT segment.
How can I do, is it possible?

**Comment by cleftheris** [comment]
Hi @FannyMaulny when dealing with optional segments you should avoid initializing them in the contructor of your container class (for example under segment group `Intervenant` you are newing `Segment_RFF`). 

```csharp
        [EdiSegmentGroup("NAD", "RFF")]
        public class Intervenant : Segment_NAD
        {
            [EdiCondition("AWR", "ACD", Path = "RFF/0/0")]
            public Segment_RFF Reference { get; set; }
            public Intervenant() {
                //Reference = new Segment_RFF();
            }
        }
```

The deserializer is build in such a way that will try to instantiate your classes using the default constructor only if it finds data inside. So there is no need to do instantiation on your own especially for optional members.

checkout the test I have made here https://github.com/indice-co/EDI.Net/blob/004630c108ad24a1336a8c1c7a9f1f82feb82b32/test/indice.Edi.Tests/SerializerTests.cs#L177

**Comment by FannyMaulny** [comment]
Thank you for your reply.
