### ISSUE TITLE
[Q] Attributes

### ISSUE THREAD

**Issue by Nekeniehl** [indice-co/EDI.Net#14]
I have made a POCO for Edifact.CONTRL (German Energy Market, and I will probably do the rest for this market).

But I'm having troubles with the use of the Attributes since I don't really know which is for what, so far I use the following attributes in the POCO

EdiMessage: Which I guess is the start of the message, the UNH Segment (ie  **UNH**+5451674C50D64+CONTRL:D:3:UN:2.0 )
EdiSegment: Any segment in the CONTRL (ie **UCI+001342651817+9907137000005:500+9912022000002:500+7**)
EdiValue: Any value inside a segment (ie UCI+**001342651817**+9907137000005:500+9912022000002:500+7
EdiElement: No idea about how to use this one
EdiPath: To specify the path.

Following the next structure for a simple CONTRL:
```
UNB+UNOC:3+9912022000002:500+9907137000005:500+160602:1849+EAE519A8366D4
	UNH+5451674C50D64+CONTRL:D:3:UN:2.0
		UCI+001342651817+9907137000005:500+9912022000002:500+7
	UNT+3+5451674C50D64
UNZ+1+EAE519A8366D4
```

```
UNB
	UNH
		UCI
	UNT
UNZ
```
 

We get the following POCO

```csharp
    [EdiMessage]
    public class CONTRLMessage
    {
        [EdiValue("X(14)", Path = "UNH/0/0")]
        public string NachrichtKey { get; set; }

        [EdiValue("X(6)", Path = "UNH/1/0")]
        public string MessageType { get; set; }

        [EdiValue("X(3)", Path = "UNH/1/1")]
        public string Version { get; set; }

        [EdiValue("X(3)", Path = "UNH/1/2")]
        public string ReleaseNumber { get; set; }

        [EdiValue("X(2)", Path = "UNH/1/3")]
        public string ControllingAgency { get; set; }

        [EdiValue("X(6)", Path = "UNH/1/4")]
        public string AssociationAssignedCode { get; set; } //AssociationAssignedCode

        public Übertragungsdatei Übertragungsdatei { get; set; }

        public CONTRLEndMessage CONTRLEndMessage { get; set; }

        public override String ToString()
        {
            String header = $"UNH+{NachrichtKey}+{MessageType}:{Version}:{ReleaseNumber}:{ControllingAgency}:{AssociationAssignedCode}'";

            return header;
        }
    }

    #region Document

    [EdiSegment, EdiPath("UNB")]
    public class HeaderDocument
    {
        [EdiValue("X(4)", Mandatory = true, Path = "UNB/0")]
        public string SyntaxIdentifier { get; set; }

        [EdiValue("9(1)", Path = "UNB/0/1", Mandatory = true)]
        public int SyntaxVersion { get; set; }

        [EdiValue("X(35)", Path = "UNB/1/0", Mandatory = true)]
        public string SenderId { get; set; }

        [EdiValue("X(4)", Path = "UNB/1/1", Mandatory = true)]
        public string PartnerIDCodeQualifier { get; set; }

        [EdiValue("X(35)", Path = "UNB/2/0", Mandatory = true)]
        public string RecipientId { get; set; }

        [EdiValue("X(4)", Path = "UNB/2/1", Mandatory = true)]
        public string ParterIDCode { get; set; }

        [EdiValue("9(6)", Path = "UNB/3/0", Format = "yyMMdd", Description = "Date of Preparation")]
        [EdiValue("9(4)", Path = "UNB/3/1", Format = "HHmm", Description = "Time or Prep")]
        public DateTime DateOfPreparation { get; set; }

        [EdiValue("X(14)", Path = "UNB/4/0", Mandatory = true)]
        public String ControlRef { get; set; }

        public override String ToString()
        {
            String header = $"UNB+UNOC:{SyntaxVersion}+{SenderId}:{PartnerIDCodeQualifier}+{RecipientId}:{ParterIDCode}+{DateOfPreparation.ToString("yyMMdd")}:{DateOfPreparation.ToString("HHmm")}+{ControlRef}'";

            return header;
        }
    }

    [EdiElement, EdiPath("UNZ/0")]
    public class FootDocument
    {
        [EdiValue("9(1)", Path = "UNZ/0/0")]
        public String MessageNumber { get; set; }

        [EdiValue("X(14)", Path = "UNZ/1/0", Mandatory = true)]
        public String DocumentRef { get; set; }

        public override String ToString()
        {
            String header = $"UNZ+{MessageNumber}+{DocumentRef}'";

            return header;
        }
    }

    #endregion

    public class CONTRL
    {
        public HeaderDocument HeaderDocument { get; set; }

        public CONTRLMessage CONTRLMessage { get; set; }

        public FootDocument FootDocument { get; set; }
    }

    [EdiSegment, EdiPath("UNT")]
    public class CONTRLEndMessage
    {
        [EdiValue("X(6)", Path = "UNT/0/0")]
        public String SegmentCounter { get; set; }

        [EdiValue("X(14)", Path = "UNT/1")]
        public string NachrichtKey { get; set; }

        public override String ToString()
        {
            String header = $"UNT+{SegmentCounter}+{NachrichtKey}'";

            return header;
        }
    }

    [EdiSegment, EdiPath("UCI")]
    public class Übertragungsdatei
    {
        [EdiValue("X(14)", Path = "UCI/0/0")]
        public String Referenz { get; set; }

        [EdiValue("9(35)", Path = "UCI/1/0")]
        public String Receiver { get; set; }

        [EdiValue("X(4)", Path = "UCI/1/1")]
        public String ReceiverMPCode { get; set; }

        [EdiValue("9(35)", Path = "UCI/2/0")]
        public String Sender { get; set; }

        [EdiValue("9(35)", Path = "UCI/2/1")]
        public String SenderMPCode { get; set; }

        [EdiValue("9(1)", Path = "UCI/3/0")]
        public String Status { get; set; }

        [EdiValue("9(2)", Path = "UCI/4/0")]
        public String SyntaxFehler { get; set; }

        [EdiValue("X(3)", Path = "UCI/5/0")]

        public String ServiceSegment { get; set; }

        [EdiValue("X(3)", Path = "UCI/6/0")]

        public String Segmentposition { get; set; }

        [EdiValue("X(3)", Path = "UCI/6/1")]

        public String Gruppenposition { get; set; }

        public List<AntwortSegment> AntwortSegment { get; set; }

        public override String ToString()
        {
            String header = $"UCI+{Referenz}+{Receiver}:{ReceiverMPCode}+{Sender}:{SenderMPCode}+{Status}'";

            return header;
        }
    }

    [EdiSegment, EdiPath("UCM")]
    public class AntwortSegment
    {
        [EdiValue("X(14)", Path = "UCM / 0 / 0")]

        public String Referenz { get; set; }

        [EdiValue("X(6)", Path = "UCM/1/0")]
        public String NachrichtenTyp { get; set; }

        [EdiValue("X(1)", Path = "UCM/1/1")]
        public String NachrichtVersion { get; set; }

        [EdiValue("X(3)", Path = "UCM/1/2")]
        public String Freigabenummer { get; set; }

        [EdiValue("X(2)", Path = "UCM/1/3")]
        public String ControllingAgency { get; set; } //UN

        [EdiValue("X(2)", Path = "UCM/1/4")]
        public String Anwendungscode { get; set; }

        [EdiValue("X(1)", Path = "UCM/2/0")]
        public String Action { get; set; } //4

        [EdiValue("9(2)", Path = "UCM/3/0")]
        public String SyntaxFehler { get; set; }

        [EdiValue("X(3)", Path = "UCM/4/0")]

        public String ServiceSegment { get; set; }

        [EdiValue("X(3)", Path = "UCM/5/0")]

        public String Segmentposition { get; set; }

        [EdiValue("X(3)", Path = "UCM/5/1")]

        public String Gruppenposition { get; set; }


        public List<FehlerSegments> FehlerSegments { get; set; }
    }

    [EdiSegment, EdiPath("UCS")]
    public class FehlerSegments
    {
        [EdiValue("X(6)", Path = "UCS/0/0")]
        public String Segmentposition { get; set; }

        [EdiValue("9(2)", Path = "UCS/1/0")]

        public String Syntaxfehler { get; set; }

        public List<Fehlerelement> Fehlerelement { get; set; }
    }

    [EdiSegment, EdiPath("UCD")]
    public class Fehlerelement
    {
        [EdiValue("9(2)", Path = "UCD/0/0")]
        public String SyntaxFehler { get; set; }

        [EdiValue("X(3)", Path = "UCD/1/0")]

        public String Segmentposition { get; set; }

        [EdiValue("X(3)", Path = "UCD/1/1")]

        public String Gruppenposition { get; set; }

    }
```

It is working as expected for the UNB, UNH, UCI, and UNT, but not for the UNZ. It is missing the DocumentRef.

Any ideas? Wrong using of attributes? Is there any docu for the attributes usage?

Thanks so much.

**Comment by Nekeniehl** [comment]
I have made it work adding the HeaderDocument (UNB) and the FootDocument (UNZ) to the CONTRL class, here the complete POCO CONTRL

`[EdiMessage]
    public class CONTRLMessage
    {
        [EdiValue("X(14)", Path = "UNH/0/0")]
        public string NachrichtKey { get; set; }

        [EdiValue("X(6)", Path = "UNH/1/0")]
        public string MessageType { get; set; }

        [EdiValue("X(3)", Path = "UNH/1/1")]
        public string Version { get; set; }

        [EdiValue("X(3)", Path = "UNH/1/2")]
        public string ReleaseNumber { get; set; }

        [EdiValue("X(2)", Path = "UNH/1/3")]
        public string ControllingAgency { get; set; }

        [EdiValue("X(6)", Path = "UNH/1/4")]
        public string AssociationAssignedCode { get; set; } //AssociationAssignedCode

        public Übertragungsdatei Übertragungsdatei { get; set; }

        public CONTRLEndMessage CONTRLEndMessage { get; set; }

        public override String ToString()
        {
            String header = $"UNH+{NachrichtKey}+{MessageType}:{Version}:{ReleaseNumber}:{ControllingAgency}:{AssociationAssignedCode}'";

            header += Übertragungsdatei;

            header += CONTRLEndMessage;
            return header;
        }
    }

    #region Document

    [EdiSegment, EdiPath("UNB")]
    public class HeaderDocument
    {
        [EdiValue("X(4)", Mandatory = true, Path = "UNB/0")]
        public string SyntaxIdentifier { get; set; }

        [EdiValue("9(1)", Path = "UNB/0/1", Mandatory = true)]
        public int SyntaxVersion { get; set; }

        [EdiValue("X(35)", Path = "UNB/1/0", Mandatory = true)]
        public string SenderId { get; set; }

        [EdiValue("X(4)", Path = "UNB/1/1", Mandatory = true)]
        public string PartnerIDCodeQualifier { get; set; }

        [EdiValue("X(35)", Path = "UNB/2/0", Mandatory = true)]
        public string RecipientId { get; set; }

        [EdiValue("X(4)", Path = "UNB/2/1", Mandatory = true)]
        public string ParterIDCode { get; set; }

        [EdiValue("9(6)", Path = "UNB/3/0", Format = "yyMMdd", Description = "Date of Preparation")]
        [EdiValue("9(4)", Path = "UNB/3/1", Format = "HHmm", Description = "Time or Prep")]
        public DateTime DateOfPreparation { get; set; }

        [EdiValue("X(14)", Path = "UNB/4/0", Mandatory = true)]
        public String ControlRef { get; set; }

        public override String ToString()
        {
            String header = $"UNB+UNOC:{SyntaxVersion}+{SenderId}:{PartnerIDCodeQualifier}+{RecipientId}:{ParterIDCode}+{DateOfPreparation.ToString("yyMMdd")}:{DateOfPreparation.ToString("HHmm")}+{ControlRef}'";

            return header;
        }
    }

    [EdiSegment, EdiPath("UNZ")]
    public class FootDocument
    {
        [EdiValue("9(1)", Path = "UNZ/0/0")]
        public String MessageNumber { get; set; }

        [EdiValue("X(14)", Path = "UNZ/1/0", Mandatory = true)]
        public String DocumentRef { get; set; }

        public override String ToString()
        {
            String header = $"UNZ+{MessageNumber}+{DocumentRef}'";

            return header;
        }
    }

    #endregion

    public class CONTRL
    {
        public CONTRLMessage CONTRLMessage { get; set; }

        [EdiValue("X(4)", Mandatory = true, Path = "UNB/0")]
        public string SyntaxIdentifier { get; set; }

        [EdiValue("9(1)", Path = "UNB/0/1", Mandatory = true)]
        public int SyntaxVersion { get; set; }

        [EdiValue("X(35)", Path = "UNB/1/0", Mandatory = true)]
        public string SenderId { get; set; }

        [EdiValue("X(4)", Path = "UNB/1/1", Mandatory = true)]
        public string PartnerIDCodeQualifier { get; set; }

        [EdiValue("X(35)", Path = "UNB/2/0", Mandatory = true)]
        public string RecipientId { get; set; }

        [EdiValue("X(4)", Path = "UNB/2/1", Mandatory = true)]
        public string ParterIDCode { get; set; }

        [EdiValue("9(6)", Path = "UNB/3/0", Format = "yyMMdd", Description = "Date of Preparation")]
        [EdiValue("9(4)", Path = "UNB/3/1", Format = "HHmm", Description = "Time or Prep")]
        public DateTime DateOfPreparation { get; set; }

        [EdiValue("X(14)", Path = "UNB/4/0", Mandatory = true)]
        public String ControlRef { get; set; }

        
        [EdiValue("9(1)", Path = "UNZ/0/0")]
        public String MessageNumber { get; set; }

        [EdiValue("X(14)", Path = "UNZ/1/0", Mandatory = true)]
        public String DocumentRef { get; set; }

        public override String ToString()
        {
            String header = $"UNB+UNOC:{SyntaxVersion}+{SenderId}:{PartnerIDCodeQualifier}+{RecipientId}:{ParterIDCode}+{DateOfPreparation.ToString("yyMMdd")}:{DateOfPreparation.ToString("HHmm")}+{ControlRef}'";

            header += CONTRLMessage;
            header += $"UNZ+{MessageNumber}+{DocumentRef}'";
            return header;
        }
    }

    [EdiSegment, EdiPath("UNT")]
    public class CONTRLEndMessage
    {
        [EdiValue("X(6)", Path = "UNT/0/0")]
        public String SegmentCounter { get; set; }

        [EdiValue("X(14)", Path = "UNT/1")]
        public string NachrichtKey { get; set; }

        public override String ToString()
        {
            String header = $"UNT+{SegmentCounter}+{NachrichtKey}'";

            return header;
        }
    }

    [EdiSegment, EdiPath("UCI")]
    public class Übertragungsdatei
    {
        [EdiValue("X(14)", Path = "UCI/0/0")]
        public String Referenz { get; set; }

        [EdiValue("9(35)", Path = "UCI/1/0")]
        public String Receiver { get; set; }

        [EdiValue("X(4)", Path = "UCI/1/1")]
        public String ReceiverMPCode { get; set; }

        [EdiValue("9(35)", Path = "UCI/2/0")]
        public String Sender { get; set; }

        [EdiValue("9(35)", Path = "UCI/2/1")]
        public String SenderMPCode { get; set; }

        [EdiValue("9(1)", Path = "UCI/3/0")]
        public String Status { get; set; }

        [EdiValue("9(2)", Path = "UCI/4/0")]
        public String SyntaxFehler { get; set; }

        [EdiValue("X(3)", Path = "UCI/5/0")]

        public String ServiceSegment { get; set; }

        [EdiValue("X(3)", Path = "UCI/6/0")]

        public String Segmentposition { get; set; }

        [EdiValue("X(3)", Path = "UCI/6/1")]

        public String Gruppenposition { get; set; }

        public List<AntwortSegment> AntwortSegment { get; set; }

        public override String ToString()
        {
            String header = $"UCI+{Referenz}+{Receiver}:{ReceiverMPCode}+{Sender}:{SenderMPCode}+{Status}'";

            if (AntwortSegment != null)
            {
                foreach (var antwort in AntwortSegment)
                {
                    header += $"{antwort}'";
                }
            }
            
            return header;
        }
    }

    [EdiSegment, EdiPath("UCM")]
    public class AntwortSegment
    {
        [EdiValue("X(14)", Path = "UCM / 0 / 0")]

        public String Referenz { get; set; }

        [EdiValue("X(6)", Path = "UCM/1/0")]
        public String NachrichtenTyp { get; set; }

        [EdiValue("X(1)", Path = "UCM/1/1")]
        public String NachrichtVersion { get; set; }

        [EdiValue("X(3)", Path = "UCM/1/2")]
        public String Freigabenummer { get; set; }

        [EdiValue("X(2)", Path = "UCM/1/3")]
        public String ControllingAgency { get; set; } //UN

        [EdiValue("X(2)", Path = "UCM/1/4")]
        public String Anwendungscode { get; set; }

        [EdiValue("X(1)", Path = "UCM/2/0")]
        public String Action { get; set; } //4

        [EdiValue("9(2)", Path = "UCM/3/0")]
        public String SyntaxFehler { get; set; }

        [EdiValue("X(3)", Path = "UCM/4/0")]

        public String ServiceSegment { get; set; }

        [EdiValue("X(3)", Path = "UCM/5/0")]

        public String Segmentposition { get; set; }

        [EdiValue("X(3)", Path = "UCM/5/1")]

        public String Gruppenposition { get; set; }


        public List<FehlerSegments> FehlerSegments { get; set; }
    }

    [EdiSegment, EdiPath("UCS")]
    public class FehlerSegments
    {
        [EdiValue("X(6)", Path = "UCS/0/0")]
        public String Segmentposition { get; set; }

        [EdiValue("9(2)", Path = "UCS/1/0")]

        public String Syntaxfehler { get; set; }

        public List<Fehlerelement> Fehlerelement { get; set; }
    }

    [EdiSegment, EdiPath("UCD")]
    public class Fehlerelement
    {
        [EdiValue("9(2)", Path = "UCD/0/0")]
        public String SyntaxFehler { get; set; }

        [EdiValue("X(3)", Path = "UCD/1/0")]

        public String Segmentposition { get; set; }

        [EdiValue("X(3)", Path = "UCD/1/1")]

        public String Gruppenposition { get; set; }

    }`

**Comment by cleftheris** [comment]
@Nekeniehl  Ok the reason behind this is that the headers and footers of Messages and Groups define a "Logical" structure for an EDI transmission. So when trying to deserialize into dotnet classes in the current implementation they are considered to go into whatever the `[EdiMessage]` attribute is appled upon. However, any other segment except those that are structural can be deserialized into separate `[EdiSegment]` decorated classes. Mabe in the future I could enhance this to be able to group properties of the header and footer separately but for the time being this is not allowed.

_from wekipedia:_

```
        Service String Advice     UNA  Optional
 +----- Interchange Header        UNB  Mandatory
 | +---   Functional Group Header   UNG  Conditional
 | | +-     Message Header            UNH  Mandatory
 | | |        User Data Segments             As required
 | | +-     Message Trailer           UNT  Mandatory
 | +---   Functional Group Trailer  UNE  Conditional
 +----- Interchange Trailer       UNZ  Mandatory
```

### Regarding attributes. 
The general rules of thumb are :

| Attribute | Description      | 
|-----------|-----------|
| __EdiValue__ | Any value inside a segment. | 
|  |UCI+__001342651817__+9907137000005:500+9912022000002:500+7 |
| __EdiElement__ | Elements are considered to be groups of values otherwise known as groups of components. One can use this attribute to deserialize into a complex class that resides inside a segment. For example this can usually be used to deserialize more than one value between `+` into a ComplexType |
|  | UCI+001342651817+9907137000005:500+__9912022000002:500__+7 |
| __EdiPath__ | To specify the path |

On your general remark I would very much appreciate you contributing POCO classes for german EDI transmitions.

Does this make sense?

**Comment by Nekeniehl** [comment]
@cleftheris Thanks you so much for the reply, I think I understand now the attributes a little bit better.

I've been requested to check out this library, and I would not mind to share the POCO classes for the following formats at some point.
APERAK, CONTRL, IFTSTA, INSRPT, INVOIC, MSCONS, ORDERS, ORDRSP, PRICAT, QUOTES, REMADV, REQOTE, UTILMD

The only problem is that this formats changes every 6 months (01.04 and 01.10), meaning that the POCO classes would be obsolete every year, as you have to provide support for the april and october version.

But first I have to check if the library suit for us, I need 4 main things from the library.
-Parsing in both directions (Success)
-Parsing to xml (No problem on that neither)
-CONTRL Generation
-APERAK Generation

For both CONTRL and APERAK generation I will try to implement something extending the Attributes or making new ones, if I can make it work I will not have any problem to share that extension too.

**Comment by cleftheris** [comment]
@Nekeniehl glad I could help. I need to start documenting this soon. Anyway, regarding the CONTRL and APERAK: if I got this right you mean the process of generating an EDI file back from the POCO classes. This is something I am currently working on  as stated in Issues #6 and #7

**Comment by cleftheris** [comment]
@Nekeniehl  Ok just found this on the german Wikipedia https://de.wikipedia.org/wiki/EDIFACT 
Since I don't speak German I google translated it and It looks like somekind of transmission validation? Can you send me some more info on this. Was I correct about what you need in my previous answer?

**Comment by Nekeniehl** [comment]
@cleftheris exactly is that (I'm not german neither) and sadly all the docu I have found it is in German or english but from 2014 or older.

You send out a message and you will receive a CONTRL (Positive or negative) saying your message was receive and it is fine (or not), syntactically speaking.

I.e if you send a segment that suppossed to be LOC and instead, you send LCO, the message would be rejected with a negative CONTRL, specifying the segment and the position where your message has incorrect. Other example would be a mandatory field missing or an incorrect optional value.

CONTRL
> A Syntax and Service Report message is a message syntactically acknowledging, or rejecting with error indication, a received interchange, or message.
[http://www.gs1.org/sites/default/files/docs/eancom/s4/contrl.pdf](url)

In the other hand the APERAK is more or less the same thing, but it checks the mandatory fields for a given process type, that means, each process type (registration, cancellation, etc) has his own sets of mandatory fields to be filled in the message. If there are the correct fields filled for that process type, you will not receive any thing, but if there are not, then you will receive an APERAK and the original message will not be proccessed by the system.

> APERAK is a message from the party who received an original message, to the party who issued the original message, to acknowlegde to the message issuer the receipt of the original message by the recipient's application and to acknowledge errors made during the processing within the application.
[http://www.gs1.org/sites/default/files/docs/eancom/s4/aperak.pdf](url)

The main documentation place is [http://www.edi-energy.de/](url) but, yep, everything in german.

I have some weeks to try out the library and see what I can do, but I'm pretty confident about it, and at least the CONTRL generation would not be so much problematic to implement as I already started to do some successfuly test and extending the attributes to support this.

**Comment by Nekeniehl** [comment]
Hey, I started to work on this again, and I just wanted to share some things I have made. 

Since the format in the German Market changes every six months, I have implemented a way to create a Runtime class based on a given Xml. This is done by Reflection.Emit, which can be use to be translated to another programming language without any problems. So the first part of the problem about the temporally POCO class and the 6 months changing version is "fixed", you just have to provide the new xml for the version and you are done.

This is how it looks:

```
<?xml version="1.0" encoding="UTF-8"?>
<CONTRL Version="2.0">
    <Syntax_Kennung EdiElement="Syntax_Kennung" EdiPath="UNB/0">
        <SyntaxID EdiValue="X(4)" EdiPath="UNB/0/0"/>
        <Sintaxversion EdiValue="9(1)" EdiPath="UNB/0/1"/>
    </Syntax_Kennung>
    <Absender EdiElement="Absender" EdiPath="UNB/1">
        <ID EdiValue="X(35)" EdiPath="UNB/1/0"/>
        <Code_UNB EdiValue="X(4)" EdiPath="UNB/1/1"/>
    </Absender>
    <Empfänger EdiElement="Empfänger" EdiPath="UNB/2">
        <ID EdiValue="X(35)" EdiPath="UNB/2/0"/>
        <Code_UNB EdiValue="X(4)" EdiPath="UNB/2/1"/>
    </Empfänger>
    <Dokumentdatum EdiElement="Dokumentdatum" EdiPath="UNB/3">
        <Datum EdiValue="X(6)" EdiPath="UNB/3/0" Format="ddMMyy"/>
        <Zeit EdiValue="X(4)" EdiPath="UNB/3/1" Format="HHmm"/>
    </Dokumentdatum>
    <Datenaustauschreferenz EdiValue="X(14)" EdiPath="UNB/4"/>
    <Nachricht EdiMessage="Nachricht">
        <Nachrichten_Referenznummer EdiValue="X(14)" EdiPath="UNH/0/0"/>
        <Nachrichten_Kennung EdiElement="Nachrichten_Kennung" EdiPath="UNH/1">
            <Nachrichtentyp EdiValue="X(6)" EdiPath="UNH/1/0"/>
            <DraftVersion EdiValue="X(3)" EdiPath="UNH/1/1"/>
            <Freigabenummer EdiValue="X(3)" EdiPath="UNH/1/2"/>
            <Verwaltende_Organisation EdiValue="X(2)" EdiPath="UNH/1/3"/>
            <Versionsnummer EdiValue="X(6)" EdiPath="UNH/1/4"/>
        </Nachrichten_Kennung>
        <Übertragungsdatei EdiSegment="" EdiPath="UCI">
            <Datenaustauschreferenz EdiValue="X(14)" EdiPath="UCI/0/0"/>
            <Absender_NAD EdiElement="Absender" EdiPath="UCI/1">
                <ID EdiValue="X(35)" EdiPath="UCI/1/0"/>
                <Code_UNB EdiValue="X(4)" EdiPath="UCI/1/1"/>
            </Absender_NAD>
            <Empfänger_NAD EdiElement="Empfänger_NAD" EdiPath="UCI/2">
                <ID EdiValue="X(35)" EdiPath="UCI/2/0"/>
                <Code_UNB EdiValue="X(4)" EdiPath="UCI/2/1"/>
            </Empfänger_NAD>
            <Status EdiValue="X(3)" EdiPath="UCI/3/0"/>
            <Syntaxfehler EdiValue="9(2)" EdiPath="UCI/4/0"/>
            <Servicesegment EdiValue="X(3)" EdiPath="UCI/5/0"/>
            <DatenelementIdentifikation EdiElement="DatenelementIdentifikation" EdiPath="UCI/6">
                <Segmentposition EdiValue="9(3)" EdiPath="UCI/6/0" />
                <Gruppenposition EdiValue="9(3)" EdiPath="UCI/6/1" />
            </DatenelementIdentifikation>
            <Nachrichtenantwort EdiSegment="" EdiPath="UCM">
                <Nachrichten_Referenznummer EdiValue="X(14)" EdiPath="UCM/0/0"/>
                <Nachrichten_Kennung_UCM EdiElement="Nachrichten_Kennung_UCM" EdiPath="UCM/1">
                    <Nachrichtentyp EdiValue="X(6)" EdiPath="UCM/1/0"/>
                    <DraftVersion EdiValue="X(3)" EdiPath="UCM/1/1"/>
                    <Freigabenummer EdiValue="X(3)" EdiPath="UCM/1/2"/>
                    <Verwaltende_Organisation EdiValue="X(2)" EdiPath="UCM/1/3"/>
                    <Versionsnummer EdiValue="X(6)" EdiPath="UCM/1/4"/>
                </Nachrichten_Kennung_UCM>
                <Status EdiValue="X(3)" EdiPath="UCM/2/0"/>
                <Syntaxfehler EdiValue="9(2)" EdiPath="UCM/3/0"/>
                <Servicesegment EdiValue="X(3)" EdiPath="UCM/4/0"/>
                <DatenelementIdentifikation_UCM EdiElement="DatenelementIdentifikation_UCM" EdiPath="UCM/5">
                    <Segmentposition EdiValue="9(3)" EdiPath="UCM/5/0" />
                    <Gruppenposition EdiValue="9(3)" EdiPath="UCM/5/1" />
                </DatenelementIdentifikation_UCM>
                <FehlerSegments EdiElement="" EdiPath="UCS">
                    <Segmentposition EdiValue="9(6)" EdiPath="UCS/0/0"/>
                    <Syntaxfehler EdiValue="9(2)" EdiPath="UCS/1/0"/>
                    <Fehlerelement EdiElement="" EdiPath="UCD">
                        <Syntaxfehler EdiValue="9(2)" EdiPath="UCD/1/0"/>
                        <Segmentposition EdiValue="9(3)" EdiPath="UCD/1/0" />
                        <Gruppenposition EdiValue="9(3)" EdiPath="UCD/1/1" />
                    </Fehlerelement>
                </FehlerSegments>
            </Nachrichtenantwort>
        </Übertragungsdatei>
        <Datenaustauschzaehler EdiValue="X(6)" Edipath="UNT/0/0/"/>
    </Nachricht>
</CONTRL>
```

I will continue forward with the CONTRL check, then APERAK and after that I will implement the other 12 formats.

Since my idea is work with attributes, I was looking at EdiAttribute classes, Could you please explain briefly what is the "Mandatory" and "Description" properties for? Thanks you so much for this library!

**Comment by cleftheris** [comment]
This is sooo cool!! It took me some time to realize what you did there and it rocks.

Regarding your questions.
1. The description property does nothing. It simply serves as a metadata comment for helping the author of the CLR model navigate around a big transmition. For example
```csharp
        [EdiValue("9(6)", Path = "UNB/3/0", Format = "yyMMdd", Description = "Date of Preparation")]
        [EdiValue("9(4)", Path = "UNB/3/1", Format = "HHmm", Description = "Time or Prep")]
        public DateTime DateOfPreparation { get; set; }
```

2. The mandatory property was designed in order to validate incoming and outgoing transmissions for the absence of a required member. It is not used (implemented) yet. This should be easy to implement but I have not found the time to do it. I have an open issue about it here #18

**Comment by cleftheris** [comment]
@Nekeniehl also I forgot to mention that since v1.1 Edi.Net can serialize back to EDI

**Comment by Nekeniehl** [comment]
Hey thanks @cleftheris, that is amazing! since the deserialization is something I really need (and I had implemented such a dirty way there with the toString..). 

I also saw an open ticket for "Relative EdiPath" ([#5)](https://github.com/indice-co/EDI.Net/issues/5) for segments that are repetitive, like "DatenelementIdentifikation" which is use in two different places. There is currently no way to use the same class with different EdiPath, right?

I will continue working on it and share all that I can! once again, thanks for the support!

**Comment by cleftheris** [comment]
@Nekeniehl . 
Issue #5 is more related to cases when an Element (a set of components) is resurfacing under different segment name. Lets say we got the `AddressInfo` complex type and it is on the second element of segment `XXX\1` and the third element of `YYY\2`. Currently there is no way to reuse class `AddressInfo` one must make two copies or subclasses of that for each location. The above problem I have found is more related to how a `TRADACOMS` transmission is layered out.

On EdiFact on the other hand when Segments used as the main org unit. So in this case the flexibility to reuse a class is fully supported. Check for example [this model](https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/Models/EdiFact01.cs) and how the DTM segment is handled.

For any additional query you may have it is preferred that you open a new issue so I can keep track of different Q&A for future visitors.
