### ISSUE TITLE
EdiTextWriter writes boolean value is wrong

### ISSUE THREAD

**Issue by daitran-zooloo** [indice-co/EDI.Net#141]
Should write 1 if value is true, otherwise 0.

public override void WriteValue(bool value) {
            InternalWriteValue(EdiToken.Boolean);
            _writer.Write(value ? 0 : 1);
        }

**Comment by cleftheris** [comment]
Clearly a bug

**Comment by cleftheris** [comment]
just pushed a release 1.9.5 to address this

**Comment by daitran-zooloo** [comment]
Awesome, thanks!
