### ISSUE TITLE
EdiSerializer.Serialize closes Stream

### ISSUE THREAD

**Issue by MovGP0** [indice-co/EDI.Net#144]
### Problem 
When writing the EDIFACT data into a memory stream, I don't want the stream to be closed, because I cannot read from a closed stream. 

### Current behaviour

Given I want to write the EDIFACT data into a memory stream rather than a file
When calling `EdiSerializer.Serialize(TextWriter, EdiGrammer, object)` 
Then the TextWriter and the underlying stream will get disposed

### Expected behaviour

Given I want to write the EDIFACT data into a memory stream rather than a file
When calling `EdiSerializer.Serialize(TextWriter, EdiGrammer, object)` 
Then the TextWriter and the underlying stream is not disposed

### Workaround

- write to a temp file
- Read the temp file back to memory
- delete the temp file

**Drawback**

Much lower performance, becase of write and read to the file system, rather than just keeping the object in memory.

**Comment by cleftheris** [comment]
Hi @MovGP0 and thanks for your interest in the library. 

There is already a handle to prevent the EdiTextWritter which is wrapping the TextWeitter you pass into the Serialize methid. Its a property called `CloseOutput` and its default value is true. You need to simply switch it off before disposing.

```csharp
            string output;
            using (var writer = new StringWriter())
            using (var ediwriter = new EdiTextWriter(writer, grammar)) {
                ediwriter.CloseOutput = false;
                new EdiSerializer().Serialize(ediwriter, interchange);
                output = writer.ToString();
            }
```

**Comment by cleftheris** [comment]
Did you manage to resolve the issue with the suggestion above. 
If so please close the issue. Otherwise feel free to give more input.

Regards,
C.
