### ISSUE TITLE
Read and Write TimeOut

### ISSUE THREAD

**Issue by AbhishekInSync47** [indice-co/EDI.Net#148]
Hello everyone, 

I am using this package for writing an EDI file using a XML packet. But i am getting **stream.ReadTimeOut** and **stream.WriteTimeOut** when using the **'ediwriter'** function. Can anyone please help me out or let me know how to resolve it. That will be very helpful.

**Thanks & Regards,**

Abhishek

**Comment by cleftheris** [comment]
Hi @AbhishekInSync47 in order to investigate your issue you need to provide with a failing transmission file and models.

**Comment by cleftheris** [comment]
closed because of inactivity
