### ISSUE TITLE
Support for segments without any data

### ISSUE THREAD

**Issue by mikkel-greenbyte** [indice-co/EDI.Net#152]
Hi!

At the time of writing, https://en.wikipedia.org/wiki/EDIFACT has the following example:

> UNA:+.? '
UNB+IATB:1+6XPPC:ZZ+LHPPC:ZZ+940101:0950+1'
UNH+1+PAORES:93:1:IA'
MSG+1:45'
IFT+3+XYZCOMPANY AVAILABILITY'
ERC+A7V:1:AMD'
IFT+3+NO MORE FLIGHTS'
ODI'
TVL+240493:1000::1220+FRA+JFK+DL+400+C'
PDI++C:3+Y::3+F::1'
APD+74C:0:::6++++++6X'
TVL+240493:1740::2030+JFK+MIA+DL+081+C'
PDI++C:4'
APD+EM2:0:1630::6+++++++DA'
UNT+13+1'
UNZ+1+1'

This example will currently fail to parse with the exception message "Invalid character after parsing segment name. Expected '+' but got: '. Path '', line 1, position 151."

This happens because the ODI segment doesn't have any data elements associated with it.

Specifically, the ParseSegmentName method in the EdiTextReader class does the following after having read the segment name:

`if (Grammar.SegmentNameDelimiter != _chars[_charPos])
    throw EdiReaderException.Create(...);`

Is there a workaround for this?

Thanks in advance,
Mikkel

**Comment by cleftheris** [comment]
If you replace the `ODI'` with `ODI+'` it would work right away. This is interesting though since I have not had a request for such a case before. This is essentially an empty segment. I will check it out.

**Comment by cleftheris** [comment]
Thanks for reporting this. Check out the latest release [v1.9.8](https://www.nuget.org/packages/indice.Edi/1.9.8) on nuget

**Comment by cleftheris** [comment]
also I drafted a quick sample for the wikipedia exmple check it out in the tests project. It is not complete but it is a draft. https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/Models/EdiFact_Issue152_Wikipedia.cs

**Comment by mikkel-greenbyte** [comment]
Thanks a lot for the quick turn around! Seems to work as expected for the [CAV](https://www.unece.org/trade/untdid/d15a/trsd/trsdcav.htm) segment I encountered in a [UTILTS](https://www.unece.org/trade/untdid/d15a/trmd/utilts_c.htm) message =)
Stay safe!
