### ISSUE TITLE
 Empty segment creation issue

### ISSUE THREAD

**Issue by ilkertura** [indice-co/EDI.Net#153]
There are empty properties on my model but they still created from fw .  I can't use mandatory option on segments. How do I ensure that it is not rendered when they are empty ?

**Comment by cleftheris** [comment]
If you are using classes to represent the segments then simply leave the properties null.
for example 

```csharp

[EdiMessage]
public class Message
{

    // other members....

    // leave this null
    public DTM LeaveMeNull { get; set; }
}

[EdiSegment, EdiPath("DTM")]
public class DTM
{
   //...
}
```
