### ISSUE TITLE
Tests fail on alternative OS

### ISSUE THREAD

**Issue by drwhalen** [indice-co/EDI.Net#155]
Three tests (ValueAttributePath_Weird_behavior_Test, SegmentWithOneElementDoesNotPrintPrecedingComponentSeparators, and WriterWrites_Boolean_Correctly) all fail on Unix and Mac OS. The test is seeking a \r\n newline. Mac X/Unix will only output \n while Mac will only output \r.

**Comment by cleftheris** [comment]
Thanks for pointing this out. 
I would much appreciate it if you can check for a workaround since I am on windows. Maybe using Environment.NewLine would work.

In anycase I will check it out
