### ISSUE TITLE
X12 850 Example

### ISSUE THREAD

**Issue by NealWalters** [indice-co/EDI.Net#158]
I'm trying to follow the concept on your StackOverflow post: 
https://stackoverflow.com/questions/2046553/edi-flat-file-parsing-with-c

I'm hung up on a couple of concepts. 

In that post you have: 
public class EDI_X12Grammar : IEdiGrammar
{
...
}

but when I search through your GitHub library, I found ...\EDI.Net-master\src\indice.Edi\EdiGrammar.cs which implements IEdiGrammar. 
It also has a comment "Essentialy these are the rules for X12, EDIFact or TRADACOMS.", so I'm wondering if it is an update to what you had on StackOverflow? 

Can I use that one, or do I need to create my own?  If I have to create my own is there any sample or model to follow? 

Second, trying to use the EdiGrammar above. 

Then trying to use that as per that StackOverflow post: 

            var grammar = new indice.Edi.EDI_X12Grammar()
            { 
                ComponentDataElementSeparator = new[] { '>' },
                DataElementSeparator = new[] { '*' },
                DecimalMark = null,
                ReleaseCharacter = null,
                Reserved = new char[0],
                SegmentTerminator = '~',
                ServiceStringAdviceTag = null,
                InterchangeHeaderTag = "ISA",
                FunctionalGroupHeaderTag = "GS",
                MessageHeaderTag = "ST",
                MessageTrailerTag = "SE",
                FunctionalGroupTrailerTag = "GE",
                InterchangeTrailerTag = "IEA",
            };

I get this error on every field: 
'EDI_X12Grammar.ComponentDataElementSeparator' cannot be used in this context because the set accessor is inaccessible. 

I'm creating an EDI Tutorial course and would like to include this. 

Thanks,
Neal

**Comment by NealWalters** [comment]
I just noticed I was using .NET Framework instead of Core, let me try same in Core tomorrow. 
Neal

**Comment by cleftheris** [comment]
Hi @NealWalters and thanks for your interest in [EDI.Net](https://github.com/indice-co/EDI.Net)

Since the stackoverflow post you refered to above I have made available a specific method called set advice that handles overriding of settings. 

So there is nothing wrong with the framework version you are using (it should work the same in any version) just try to use the syntax below

```csharp
            var grammar = EdiGrammar.NewX12();
            grammar.SetAdvice(
                segmentNameDelimiter: '*', 
                dataElementSeparator: '*', 
                componentDataElementSeparator: '>', 
                segmentTerminator: '~', 
                releaseCharacter: null, 
                reserved: null, 
                decimalMark: '.');
```
This allows you to create a variation of the X12 syntax by manipulating only the delimiters/seperators which is almost always the case. If for any reason you need to control the well known tag/element names then you will need to subclass the `EdiGrammar`

```csharp
    public class MyCustomEdiGrammar : EdiGrammar
    {
        /// <summary>
        /// Constructs an <see cref="EdiGrammar"/> with the MyCustom defaults
        /// </summary>
        public EdiGrammar() : base () {
            SegmentNameDelimiter = '*',
            ComponentDataElementSeparator = '>',
            DataElementSeparator = '*',
            DecimalMark = '.',
            ReleaseCharacter = null,
            Reserved = new char[0],
            SegmentTerminator = '~',
            ServiceStringAdviceTag = null,
            InterchangeHeaderTag = "ISA",
            FunctionalGroupHeaderTag = "GS",
            MessageHeaderTag = "ST",
            MessageTrailerTag = "SE",
            FunctionalGroupTrailerTag = "GE",
            InterchangeTrailerTag = "IEA",
        }
    }
```

**Comment by NealWalters** [comment]
Thanks, much!  Very nice!  Got it working. 

I normally do EDI with BizTalk, but as mention above, creating an Intro EDI course, and showing people what they can do with parsing themselves or using libraries like yours.  So now I will highly recommend it. 

I was a little confused on what you meant by "Interchange", but that's just the POCO class/object.  Then it took few minutes to absorb the hierarchical structure.   More samples, and more documentation is always good.  For X12, I think the 850 is the one doc everyone can identify with. 

You may have an error in your file: indice.Edi.Tests\Models\X12_850.cs .

The Buyer's PartNum didn't match your sample file. 
But it was a good for me to understand changing the attribute/decorator: 
            [EdiValue(Path = "PO1/6", Description = "PO107 - Buyer’s Part #.")]
The vendor's part number may need to be lowered by two as well. 
Example 850: https://www.erico.com/public/library/edi/ERICO850_4010.pdf 


Below is some code that I think would help a new person to understand. 

Instructions for an easy X12 demo: 
1) Create new C# console program, put code below in the program.cs. 
2) Click "add" then "existing item", and select indice.Edi.Tests\Models\X12_850.cs (from the GitHub zip download). 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO; 
using indice.Edi.Tests.Models;  // for the PurchaseOrder850 added 
using indice.Edi; 

namespace EDIDevDemo
{

    class Program
    {
        static void Main(string[] args)
        {
            var inputEDIFilename = @"c:\EDIClass\Downloads\EDI.Net-master\test\indice.Edi.Tests\Samples\x12.850.edi"; 

            var grammar = EdiGrammar.NewX12();
            grammar.SetAdvice(
                segmentNameDelimiter: '*',
                dataElementSeparator: '*',
                componentDataElementSeparator: '>',
                segmentTerminator: '~',
                releaseCharacter: null,
                reserved: null,
                decimalMark: '.');
            
            var po850 = default(PurchaseOrder_850);
            using (var stream = new StreamReader(inputEDIFilename))
            {
                po850 = new EdiSerializer().Deserialize<PurchaseOrder_850>(stream, grammar);

                // If you have only one ST and one PO/850 per file, 
                // you can use subscripts, 
                // otherwise you will need loops here. 
                Console.WriteLine("PO Number:" + po850.Groups[0].Orders[0].PurchaseOrderNumber);
                Console.WriteLine("PO Date:" + po850.Groups[0].Orders[0].PurchaseOrderDate);

                foreach (var lineitem in po850.Groups[0].Orders[0].Items)
                {
                    Console.WriteLine("LineItem:"); 
                    Console.WriteLine("  Line=" + lineitem.OrderLineNumber);
                    Console.WriteLine("  Qty=" + lineitem.QuantityOrdered);
                    Console.WriteLine("  Price=" + lineitem.UnitPrice);
                    Console.WriteLine("  PartNo=" + lineitem.BuyersPartno); 
                    Console.WriteLine("  Descr=" + lineitem.ProductDescription);
                }
                // Do something with your data, such as: 
                // 1) store PO into Database 
                //       (create SQL statements or call Stored Proc) 
                // 2) right to XML for ERP system 
                // 3) call some web service to process it 

            }
            Console.WriteLine("\n\n Press enter to end:");
            Console.ReadLine(); 
        }
    }
}


One other suggestion is for error handling.  I did a stupid think and put an xml filename instead of a EDI filename for my input.  For X12, you can check if first 3 characters are not ISA then give a friendly error that the file does not begin with ISA header. Without something like that, a beginner can see odd subscript errors or something and thinks he might have to debug through your code.

**Comment by NealWalters** [comment]
Blogged here: 
http://mylifeismymessage.net/edi-net-library-for-processing-edi-files/
I made a video today, will probably put on YouTube in a few weeks.

**Comment by cleftheris** [comment]
Thanks for all the valuable suggestions. I have been meaning to update the readme as well as moving more stuff discussed in questions to the wiki pages. This would make a good start for a meaningful documentation. If you feel like contributing to the wiki feel free! 

Although the samples are a collection of models and samples contributed from people the where usually stuck in some part of the library and are often incomplete its good to know that 850 is the most popular for beginners.

Thanks again!
