### ISSUE TITLE
Don't escape decimal character in text value

### ISSUE THREAD

**Issue by Charpy49** [indice-co/EDI.Net#162]
Hello,
I saw the issue #160 
but I cant figure out to work with EscapeDecimalMarkInText = false
I serialize to EdiFact
And i have this result
`IMD+F+35+::::Noir mat int?. gun - Gun fonce'`
but I want this result (with out the escape character before the point
`IMD+F+35+::::Noir mat int. gun - Gun fonce'`
I precise that the decimal separator is the point,
I have the v1.9.11 of the library
thanks in advance

**Comment by cleftheris** [comment]
Thanks for reporting. Please checkout v1.9.12

**Comment by Charpy49** [comment]
thanks for your Help
