### ISSUE TITLE
Question: Having repeating MSG lines on X12 850

### ISSUE THREAD

**Issue by bangerlm** [indice-co/EDI.Net#168]
Hello I would greatly appreciate some help.

I am trying to serialize a X12 850 to handle really long msg's, There is a 264 character limit so I need multiple lines, but when I have tried to create a list of MSG's the library is grouping the MSG's two items per line

For a testing example I want 3 MSG lines, but when I serialize it I am getting 2 MSG lines with the first two being concatenated together with the ComponentDataElementSeparator between.  I have gone through the code, but can't figure out how to make it so each line is on its own line

Here is test I created in the example/test code
```csharp
public void Purchase_Order_850_MSG_TEST_Sample() {
            PurchaseOrder_850 eightFifty = new PurchaseOrder_850();

            Order order = new Order();
            eightFifty.Groups = new List<FunctionalGroup>();
            FunctionalGroup group = new FunctionalGroup();
            group.Orders = new List<Order>();
            Order order1 = new Order();
            order1.Items = new List<OrderDetail>();
            group.Orders.Add(order1);

            eightFifty.Groups.Add(group);
            eightFifty.Groups[0].Orders.Add(order);

            int orderIndex = eightFifty.Groups[0].Orders.Count - 1;

            eightFifty.Groups[0].FunctionalIdentifierCode = "PO";
            eightFifty.Groups[0].ApplicationSenderCode = "test";
            eightFifty.Groups[0].ApplicationReceiverCode = "test";
            eightFifty.Groups[0].Date = DateTime.Now;
            eightFifty.Groups[0].GroupControlNumber = 1000 + 1000; 
            eightFifty.Groups[0].GroupTrailerControlNumber = eightFifty.Groups[0].GroupControlNumber;
            eightFifty.Groups[0].AgencyCode = "X";
            eightFifty.Groups[0].Version = "test";

            OrderDetail detail = new OrderDetail();
            detail.OrderLineNumber = "001";
            detail.QuantityOrdered = 1;
            detail.UnitPrice = 10;

            MSG msg1 = new MSG();
            msg1.MessageText = "aaa1";
            MSG msg2 = new MSG();
            msg2.MessageText = "bbb2";
            MSG msg3 = new MSG();
            msg3.MessageText = "ccc3";

            detail.MSG = new List<MSG>();
            detail.MSG.Add(msg1);
            detail.MSG.Add(msg2);
            detail.MSG.Add(msg3);

            eightFifty.Groups[0].Orders[0].Items.Add(detail);
           
            string fileName = @"H:\Data\temp\EDI\test.out";
            var grammar = EdiGrammar.NewX12();

            using (var textWriter = new StreamWriter(System.IO.File.Open(fileName, FileMode.Create))) {
                using (var ediWriter = new EdiTextWriter(textWriter, grammar)) {
                    new EdiSerializer().Serialize(ediWriter, eightFifty);
                }
            }

            string edi = System.IO.File.ReadAllText(fileName);
            edi = edi.Replace(System.Environment.NewLine, String.Empty);
            System.IO.File.WriteAllText(fileName, edi);
            string rawEdi = System.IO.File.ReadAllText(fileName);

            Assert.DoesNotContain("a1>b", edi);            
 }

```
And the piece of the resulting output that I don't want:
```
MSG*aaa1>bbb2~
MSG*ccc3~
```

I want it to be
```
MSG*aaa1~
MSG*bbb2~
MSG*ccc3~
```

For this example I am using the sample code X12_850.cs 
https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/Models/X12_850.cs

So I have a 

```csharp
[EdiElement, EdiPath("MSG/0")]
public class MSG
{

            [EdiValue(Path = "MSG/0", Description = "MSG01 - Message Text")]
            public string MessageText { get; set; }
}
```

and

` public List<MSG> MSG { get; set; }`

as a member of the OrderDetail class

**Comment by cleftheris** [comment]
Hi @bangerlm and thank you for your interest in [EDI.Net](https://github.com/indice-co/EDI.Net).

Keep in mind that the samples available are not considered to be complete models for their respective transmissions. Their serving purpose is to check a functional part of the library. 

That said first thing I see in your code is that in order for your MSG to be placed on a different line there must be a class that represents a the Segment name "MSG". This will work only if you decorate the class with `[EdiSegment, EdiPath("MSG")]`. In your code fragment above I only see the MSG decorated with an `EdiElement` which is supposed to emit a new element

If you could make a pull request with a new test case to the test project + a failing assertion I could review this.

**Comment by cleftheris** [comment]
Hi @bangerlm can you please check with the latest release v1.9.17 and confirm that the issue is resolved?
