### ISSUE TITLE
Weird number formatting

### ISSUE THREAD

**Issue by bugproof** [indice-co/EDI.Net#169]
e.g. `[EdiValue("9(5)", Path = "GID/0/0")]` with value 5 serializes to 00005 . Is there anyway to serialize without zeroes at the beginning?

**Comment by cleftheris** [comment]
Try the following
[EdiValue("9(1)", Path = "GID/0/0")]

It will get rid of the padding

**Comment by bugproof** [comment]
@cleftheris but will it deserialize fine even numbers like 20?

**Comment by bugproof** [comment]
is it possible to somehow optionally include decimal places? e.g. if it's 2.0 just serialize 2 without .0

**Comment by cleftheris** [comment]
You can checkout all the options for the EdiValue by eximining the tests 
- When serializing [ToEdiStringTests](https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/ToEdiStringTests.cs)
- When parsing [ParseTests](https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/ParseTests.cs)

**Comment by bugproof** [comment]
Is it possible to use `9(1)V9(2)` format but serialize e.g. `2.00` as just `2` ?

**Comment by cleftheris** [comment]
Nope this `9(1)V9(2)` is equivelant to `0.00` in c# string format.
```csharp
double value = 2.0;
Console.WriteLine(value.ToString("0.00"))
```
which outputs "2.00".

If you need just `2` plain then use  `9(1)` is equivelant to `0.#` in c# string format.
which will have the following 

double value = 2.0 --> "2"  
double value = 2.23 --> "2.23"  
double value = 2.2 --> "2.2"  
etc

**Comment by bugproof** [comment]
`9(1)` and `9(0)` gives me values like `243.60000000` for `decimal` type

**Comment by cleftheris** [comment]
> 9(1) and 9(0) give me values like 243.60000000 for decimal type,

This does not seem right. Please recheck the test cases.

> so it seems like it's not possible to have 243.60 and just 243 for 243.00

What you are asking is not consistent. You would need two different masks to achieve this with any format notation.

> why use COBOL picture clauses to define the types

this library was originally made in order to assist with TRADACOMS transmissions project I had (UK only EDI standard before EDIFact became a thing). There the format of the component values are defined using the COBOL Picture. I am free to contributions for aditional `ValueFormats`.
