### ISSUE TITLE
Failing to attach three levels of similar segments with conditions

### ISSUE THREAD

**Issue by maximeshift** [indice-co/EDI.Net#172]
Hi,
Thanks a lot for the hard work on this powerful lib.

I am struggling to handle cases with three levels of similar segments in each other. I tried with a very simple example and can't make it work.
I have the following sample :
```
AA*1*NAME 1~
BB*ADDITIONAL NAME 1~
AA*2*NAME 2~
BB*ADDITIONAL NAME 2~
AA*3*NAME 3~
BB*ADDITIONAL NAME 3~
AA*2*NAME 4~
BB*ADDITIONAL NAME 4~
```

Containing only the following segments:
```cs
[EdiSegment, EdiPath("AA")]
public class AA
{
    [EdiValue("X(3)", Path = "AA/0", Description = "AA01")]
    public string TypeCode { get; set; }

    [EdiValue("X(80)", Path = "AA/1", Description = "AA02")]
    public string Name { get; set; }
}
[EdiSegment, EdiPath("BB")]
public class BB
{
    [EdiValue("X(80)", Path = "BB/0", Description = "BB01")]
    public string OtherName { get; set; }
}
```

I built a 3 level container class like :
```cs
[EdiSegmentGroup("AA", "BB"), EdiCondition("1", Path = "AA/0")]
public class HighLevelName : AA
{
    public BB OtherName { get; set; }
    public List<MidLevelName> MidLevelNames { get; set; }
}

[EdiSegmentGroup("AA", "BB"), EdiCondition("2", Path = "AA/0")]
public class MidLevelName : AA
{
    public BB OtherName { get; set; }
    public List<LowLevelName> LowLevelNames { get; set; }
}

[EdiSegmentGroup("AA", "BB"), EdiCondition("3", Path = "AA/0")]
public class LowLevelName : AA
{
    public BB OtherName { get; set; }
}
```

When deserializing the sample I manage to get only Name 1 and Name 2, but I lose the LowLevelName Name 3 and I also lose the subsequent MidLevelName Name 4. I guess this has to do with not properly ending my SegmentGroups. But I would need to add EdiCondition on the sequence end as some AA would be included in the current segment.
Is there a way I can properly handle such cases ?

Side remark, it looks like parsing a field as long does not work. I get a proper value when parsing it as int but using long ends up with a default 0 value. Is it intended ?
Thanks a lot,

**Comment by cleftheris** [comment]
I will look into it. Search for the tests project there is a case with nested segment groups.

The long type not being parsed is definitely a bug

**Comment by maximeshift** [comment]
Hi, thanks for the quick action on the long parsing. I am not sure the parsing errors are properly handled. Whenever a field can not be parsed it usually retrieves the default value of the field instead of triggering an issue. I face it with DateTime where my format was not correct and I got a default datetime with no parsing error.
I will have another look at the test for the nesting of segments.
Thanks

**Comment by maximeshift** [comment]
Hi @cleftheris  I managed to create a failing test illustrating this multi level nesting. Should I push it in a branch directly in this repo ? Or rather in mine ?

**Comment by cleftheris** [comment]
Hi you could make a pull request so I can check it out.

**Comment by maximeshift** [comment]
HI sorry I did a wrong click, I wanted to leave in my forked repo for now.
https://github.com/maximeshift/EDI.Net/pull/1

**Comment by cleftheris** [comment]
No it's just fine as a pull request

**Comment by cleftheris** [comment]
@maximeshift  This should be resolved in the latest release. Feel free to check it out

**Comment by maximeshift** [comment]
Thanks a lot for your quick fix. I'll check it out.

**Comment by maximeshift** [comment]
Works great thanks !
