### ISSUE TITLE
I have 3 elements with the same name, how to read them ?

### ISSUE THREAD

**Issue by guido-gtt** [indice-co/EDI.Net#174]
I am having troubles in constructing my custom classes to read an EDIFACT file

here is the part in the EDI file that I have trouble with.
(the actual file is one large line, I splitted it here for better reading)

    'GIN+CN+KL1SF69WJAB150138
    'RFF+ZLS
    'TDT+30+++++ADA17991
    'DLM+++N:Z05:ZGM
    'GIR+1+0050PC36:VV+HI19671001:ZBX+1AK69  GU58:ZMC+XAAY:ZCC+060559KA:ZEE
    'GIR+1+F14D4:ZEP+T0118:ZCK+L:ZTD+AC8 AHU ALU AR9 A32 CR7 LHD NPH NT4:ZOS+ N33 P2W TDK TDW TR6 TS6 TUQ TVF T2:ZOS
    'GIR+1+C T61 T84 T9E T90 UPX WAL W6B XAAYX:ZOS+A6 XXZC41P:ZOS
    'MEA+WT+AAE+KGM:1155
    'LOC+Z0+RO0410:Z07:ZGM
    'LOC+Z05+RO0410:Z07:ZGM
    'LOC+Z02+ROBUKDZ
    'LOC+Z04+ROBUKDZ

The trouble is the 3 lines starting with GIR

I have no means of identifing them using `[EdiCondition]` so if I just try reading them, I only get the values of the 3th line

this is my class structure

```csharp
    [EdiElement, EdiPath("GIR", Path ="GIR/*")]
    public class GoodsRelatedIdentification
    {
        [EdiValue("X(3)", Path ="GIR/1/0")]
        public string SetIdentificationQualifier { get; set; }
    
        [EdiValue("X(35)", Path = "GIR/2/0")]
        public string IdentityNumber { get; set; }
    
        [EdiValue("X(3)", Path = "GIR/2/1")]
        public string IdentityNumberQualifier { get; set; }
    }
```

and its called inside this class

```csharp
    [EdiSegment, EdiSegmentGroup("GIN", SequenceEnd = "GIN")]
    public class VehicleRecord
    {
        [EdiValue("X(3)", Path = "GIN/0/0")]
        public string IdentityNumberQualifier { get; set; }
    
        [EdiValue("X(17)", Path = "GIN/1/0")]
        public string VehicleIdentificationNo { get; set; }
    
        public GIN_Reference RFF { get; set; }
    
        [EdiCondition("30", Path = "TDT/0/0")]
        public DetailsOfTransport_30 TDT_30 { get; set; }
    
        public GIN_DeliveryLimitations DLM { get; set; }
    
        public GoodsRelatedIdentification GIR { get; set; }
    }
```

When I try it like this, only the 3th GIR line is read, the first 2 are skipped.
How can I make it that all 3 lines are being read ?

**Comment by cleftheris** [comment]
Hi there are multiple things going on in this model. 

1. First of all you can not have two different element paths bound to the same container class that is marked as `EdiElement`. 
2. There cannot be a class defined with EdiElement for a segment name without a contaner EdiElement with the same name
3. You are using the wildcard notation for the `GIR/*` elements but there is neither multiple properties inside a 'GIR' segment class nor a List of GIR defined.
4. If the structure of the elements inside a segment (GIR in your case) is the same except for some of them. You can use the range notation in the path as in this example here https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/Models/EdiFact_Issue170_ElementList.cs
4. Your segment group is better defined by specifying all direct segment names contained. Also there is no need to escaping the segment group with sequenceEnd if the segment name that escapes the group is the same as the segment that starts it.

Consider something like the following and work your way through

```csharp
        [EdiElement]
        public class IdentificationNumber
        {
            [EdiValue("X(35)", Path = "*/*/0")]
            public string ObjectIdentifier { get; set; }

            [EdiValue("X(3)", Path = "*/*/1")]
            public string ObjectIdentificationCodeQualifier { get; set; }

            [EdiValue("X(3)", Path = "*/*/2")]
            public string StatusDescriptionCode { get; set; }

            public override string ToString() => $"{ObjectIdentifier}";
        }

        [EdiSegment, EdiPath("GIR")]
        public class RelatedIdentification
        {
            [EdiValue("X(3)", Path = "GIR/0/0")]
            public string SetIdentificationQualifier { get; set; }

            [EdiPath("GIR/1..*")]
            public List<IdentificationNumber> Numbers { get; set; }

            public override string ToString() => $"{SetIdentificationQualifier} ({Numbers.Count})";
        }

        [EdiSegment, EdiPath("GIN")]
        public class GIN
        {
            [EdiValue("X(3)", Path = "GIN/0/0")]
            public string IdentityNumberQualifier { get; set; }

            [EdiValue("X(17)", Path = "GIN/1/0")]
            public string VehicleIdentificationNo { get; set; }
        }

        [EdiSegment, EdiPath("RFF")]
        public class Reference
        {
            [EdiValue("X(3)", Path = "RFF/0/0")]
            public string CodeQualifier { get; set; }
            [EdiValue("X(70)", Path = "RFF/0/1")]
            public string Identifier { get; set; }
            [EdiValue("X(6)", Path = "RFF/0/2")]
            public string DocumentLineIdentifier { get; set; }
            [EdiValue("X(35)", Path = "RFF/0/3")]
            public string ReferenceVersionIdentifier { get; set; }
            [EdiValue("X(6)", Path = "RFF/0/4")]
            public string RevisionIdentifier { get; set; }

            public override string ToString() => $"{Identifier} {DocumentLineIdentifier} {ReferenceVersionIdentifier} {RevisionIdentifier}".Trim();
        }

        [EdiSegmentGroup("GIN")]
        public class VehicleRecord : GIN
        {
            public Reference RFF { get; set; }
            public List<RelatedIdentification> GIR_List { get; set; }
        }
```

**Comment by guido-gtt** [comment]
Thank you for your reply, I will study it.
If only there was some documentation or manual, I have to figure it all out by try and error

**Comment by cleftheris** [comment]
@guido-gtt you are correct about the lack of documentation but this is an opensource project. 
I am always open for contributions regarding the wiki though 😎.

**Comment by guido-gtt** [comment]
Will this produce a result where I have a list of vehicles (the part GIN until LOC repeats itself multiple time, each time with different values) where each vehicle will have a class for GIN, GIR, RFF and so on ?

**Comment by guido-gtt** [comment]
I am trying to accomplish something like this

![image](https://user-images.githubusercontent.com/24936611/97170558-2fd0b780-178c-11eb-81ff-adae4e011ab0.png)

**Comment by cleftheris** [comment]
The model I showed is not complete but if you structure correctly the rest of your segments & groups it will work great. What you ask is too generic for me to answer without writing the whole transmission model.

**Comment by guido-gtt** [comment]
Thank you for your time, but without any knowledge or documentation I just do not have a clue what I am doing.
I have no idea what a segment or a group or an element is, and how to make it work. So I am just trying something here

What would it cost me for you to write the complete transmission model ? I have a sample file and some documentation about how they set the file up, all tough it does not always seems to match the content of the sample file. But maybe that is my lack of knowledge of EDI

**Comment by cleftheris** [comment]
it is more an issue of availability than cost. I like maintaining the lib but answering all these issues can be overwhelming at times. If you still want some guidance from me the best thing is to fork the repo and add your sample transmission and the POCOs to a pull request 

I already make a test for you so you will just have to edit the files and add some more assertions
1.  Sample transmission goes here [edifact.Issue174.edi](https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/Samples/edifact.Issue174.edi)
2. Sample classes go here [EdiFact_Issue174.cs](https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/Models/EdiFact_Issue174.cs)
3. Test case to enhance is here https://github.com/indice-co/EDI.Net/blob/2e715bb1f913ffe907ade3c1812a1832041f5137/test/indice.Edi.Tests/EdiTextReaderTests.cs#L1054

C.
