### ISSUE TITLE
Segmentgroup with  variable segment ends doesnt populate

### ISSUE THREAD

**Issue by ronnyvdweyer** [indice-co/EDI.Net#193]
Hi,
I have a segmentgroup that has a variable number of end segments ... what i did is ...

```C#
    public class ResponseCPDMessage
    {
        public List<REF> AWBorBOLNumber { get; set; }
        public List<ERR> Errors { get; set; }
        public List<SG1> GoodsItems { get; set; }
    }

    [EdiSegmentGroup("CIT", SequenceEnd = "ERR")]
    public class SG1
    {
        //CIT-ERR
        public CIT ItemId { get; set; } //49
        public List<ERR> Errors { get; set; }
    }
```

When i deserialize it .. the Errors  populates but the start element CIT is always zero.

any idea how to approach this? 
Thanks
Ronny

**Comment by cleftheris** [comment]
Hi @ronnyvdweyer and thanks for your interest in [Edi.Net](https://github.com/indice-co/EDI.Net).

This issue is an FAQ. You can check previous replies on the subject "loop" or "group" on the issues tab.
Also check these answers for reference.

#171 (comment)
#176 (comment)
