### ISSUE TITLE
EdiCondition how to

### ISSUE THREAD

**Issue by GingerNinjaa** [indice-co/EDI.Net#203]
Hi, 
I try to create POCO file to mach EDIFACT INVOIC, I have problem with EdiCondition,

My case is simple i have SG6 and SG52 in "main" Message I want to create condition to check if TAX is already behind UNS. Can someone help me with that?

UNA:+.? '
UNB+IATB:1+6XPPC:ZZ+LHPPC:ZZ+940101:0950+1'
UNH+12+INVOIC:D:01B:UN:EAN011'
...
TAX+7+VAT+++:::11+S'
MOA+124:111.11
...
UNS+S'
...
TAX+7+VAT+++:::77.77+S'
MOA+777:777.77'
...
 UNT+13+1'
UNZ+1+1'

![image](https://user-images.githubusercontent.com/49481082/136209829-cace1b40-2aca-46e1-9008-003c2682434e.png)

![image](https://user-images.githubusercontent.com/49481082/136209884-68ea5c88-6629-4615-87c3-ee9c19207699.png)

**Comment by GingerNinjaa** [comment]
Do you find my pull request?

**Comment by cleftheris** [comment]
related to #204

**Comment by cleftheris** [comment]
Ok I have checked it out. Sorry for the late reply. 

What you need is to limit the segments that get put into one list and some others to be put on another list of the same type (TAX group essentially). While this is easily done using conditions on component values in your case there isnt a type that discriminates the two lists. What you need is a virtual segment group that encapsulates your UNS (summary row). 

Please check the model I have tweaked a little for you[ here ](https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/Models/Edifact_Issue203.cs)

**Comment by GingerNinjaa** [comment]
Hi, 
Thank you for your time.

I will check this tommorow and let you know about the resoult.

**Comment by GingerNinjaa** [comment]
Thank You. This solve my problems.
