### ISSUE TITLE
Serializer : Picture definition isn't using decimal precision

### ISSUE THREAD

**Issue by warmadmax** [indice-co/EDI.Net#206]
Hi there,
currently getting to grips with EDI.Net and it serialization

I've got an issue with the EdiValue when used with the 9(3)V999 format,
stepping through a forked copy, it appears that SerializeStructure is having issue with the precision part of the picture always being 0 when it gets to writer.WriteValue(value, property.ValueInfo.Picture, property.ValueInfo.Format);

which means any decimals I send through are stripped of decimal place values.

Class of one the more heavily affected segments

```csharp
[EdiSegment][EdiSegmentGroup("ILD", SequenceEnd = "STL")]
public class ILD {
    [EdiValue("9(10)", Path = "ILD/0")]
    [EdiGenerated(EdiGeneratedType.Position, EdiStructureType.Segment)]
    public int SEQA_SequenceNo1 { get; set; } = 1;

    [EdiValue("9(10)", Path = "ILD/1")]
    [EdiGenerated(EdiGeneratedType.Position, EdiStructureType.SegmentGroup)]
    public int SEQB_SequenceNo2 { get; set; } = 1;

    [EdiValue("9(13)", Path = "ILD/2/0")]
    public long SPRO_SuppliersEANCode { get; set; }

    [EdiValue("X(30)", Path = "ILD/2/1")]
    public string SPRO_SuppliersItemCode { get; set; }

    [EdiValue("9(13)", Path = "ILD/4/0")]
    public long CPRO_CustomersEANCode { get; set; }

    [EdiValue("X(30)", Path = "ILD/4/1")]
    public string CPRO_CustomersItemCode { get; set; }

    [EdiValue("9(15)", Path = "ILD/5")]
    public long UNOR_ConsumerUnitsInTradedUnit { get; set; } = 1;

    [EdiValue("9(15)", Path = "ILD/6")]
    public long QTYI_TradedUnitsInvoiced { get; set; } = -1;

    [EdiValue("9(10)V9999", Path = "ILD/7")]
    public decimal AUCT_CostPriceExVat { get; set; }

    [EdiValue("9(10)V9999", Path = "ILD/8")]
    public long LEXC_LineTotalExVat { get; set; } = -1; // this is AUCT(price) x QTYI(qty)

    [EdiValue("X(1)", Path = "ILD/9")]
    public string VATC_VatRateCode { get; set; } = "S";

    [EdiValue("9(3)V999", Path = "ILD/10")]
    public decimal VATP_VatRatePercent { get; set; } = 20;

    [EdiValue("X(30)", Path = "ILD/13")]
    public string TDES_TradedUnitDescLine1 { get; set; } = "";
}

```

**Comment by cleftheris** [comment]
1. Use `9(1)` whenever you got an integer and you do not need padding. 
2. Use this `9(10)V9(4)` instead of `9(10)V9999`. Unfortunately the latter notation is not supported.
3. Also use the decimal mark picture as you would use the string format. For example `9.93` with `9(10)V9(4)` translates to `0000000009.93` like it would if you did `int n = 9.93; n.ToString("0000000000.0###")` so you are better of starting with `9(1)V9(4)`

**Comment by warmadmax** [comment]
Thanks for coming back to me @cleftheris 
That's sorted out my issues regarding decimals and padding
