### ISSUE TITLE
Question - Any way to disable the padding of numerics?

### ISSUE THREAD

**Issue by warmadmax** [indice-co/EDI.Net#207]
as per title, is there any option built in to not pad out numeric values with leading zeros?

**Comment by cleftheris** [comment]
Hi @warmadmax 

Please check the following tests that show cases the available options. The short answer is yes.

https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/ToEdiStringTests.cs

C.

**Comment by warmadmax** [comment]
thanks @cleftheris 
your other response using 9(1) sorted my padding issue out.
