### ISSUE TITLE
Auto Generate POCO

### ISSUE THREAD

**Issue by dvddo** [indice-co/EDI.Net#209]
Is it possible to auto generate class like EdiFact_Issue152_Wikipedia_Transmission.cs based on schema or XSD files? I would like to create a ITAREQ, TKTREQ ... for IATA.

**Comment by cleftheris** [comment]
Hi @dvddo I am not sure I understand the question. The library is based on the foundation that you have described the spec for the transmission via dotnet attribute annotations. Theoretically one could make a dynamic class via Roslyn compiler and load that. Why you would need to generate the class based on schema. I suppose that these 3 are fixed transmissions. If you have all tree transmission types in classes you could serialize from and to an EDI text stream.

**Comment by dvddo** [comment]
Perhaps i misunderstand how the edi.net work. EdiFact_Issue152_Wikipedia_Transmission.cs is a POCO. It is used to translate the PAORES 93.1A message. If i give it a PAOREQ 93.1A message i need a separate POCO for it. Is this is not true for other IATA Edifact messages also? If is the case, i need to create a new POCO for each different version of the Edifact 98.1A, 98.1B, 2001.1A, 2001B and so forth. There could be potentially thousands of template so building each one from scratch seems daunting. I am familiar with biztalk and believe it uses xsd file for translate PNRGOV messages into xml. I wonder if it it can be done here also? Would love to contribute to this project this is something worthwhile.

**Comment by dvddo** [comment]
Thank you for looking into this. I understand your time needs to be manage correctly. POCO files are really up to user to create. I will try to create one from scratch to see what is involved. All of the documentation should be found in the issues search or is there a separate section i can find it?

Thanks again.

**Comment by cleftheris** [comment]
Hi @dvddo,

there is no documentation unfortunately you will have to dig into the issues. But I have strived to answer as many as I can so there is a big deal of information.

I wish I did have the time to extract that into a wiki docs folder.
