### ISSUE TITLE
How to map UNB segment in POCO file?

### ISSUE THREAD

**Issue by GingerNinjaa** [indice-co/EDI.Net#210]
Hi,

I have a problem with deserializing UNB segment from the source file.

In my POCO i create a class for this segment but after i run my program this class have null value. 

How I can map UNB segment in my poco ?

**Comment by GingerNinjaa** [comment]
Hi, 

Belowe is the sample from my input file. And I want to map UNB in my poco so in ordert to do this, I create class. But this is not working and I dont know why

UNA:+.? '
UNB+UNOA:3+5412345678908:14+8798765432106:14+020102:1000+1'

Sample code 


        [EdiMessage]
        //[Serializable]
        //[JsonProperty("INVOIC")]
        [XmlRoot(ElementName = "INVOIC")]
        public class Message
        {
            [JsonProperty("UNB")]
            [XmlElement(ElementName = "UNB")]
            public UNB UNB { get; set; }

            [JsonProperty("UNH")]
            [XmlElement(ElementName = "UNH")]
            public UNH UNH { get; set; }

            [JsonProperty("BGM")]
            [XmlElement(ElementName = "BGM")]
            public BGM BGM { get; set; }

            [JsonProperty("DTM")]
            [XmlElement(ElementName = "DTM")]
            public List<DTM> DTM { get; set; }

            [JsonProperty("PAI")]
            [XmlElement(ElementName = "PAI")]
            public PAI PAI { get; set; }

            [JsonProperty("ALI")]
            [XmlElement(ElementName = "ALI")]
            public List<ALI> ALI { get; set; }

            [JsonProperty("FTX")]
            [XmlElement(ElementName = "FTX")]
            public List<FTX> FTX { get; set; }

            [JsonProperty("SG1")]
            [XmlElement(ElementName = "SG1")]
            public List<SG1> SG1 { get; set; }

            [JsonProperty("SG2")]
            [XmlElement(ElementName = "SG2")]
            public List<SG2> SG2 { get; set; }

            [JsonProperty("SG6")]
            [XmlElement(ElementName = "SG6")]
            public List<SG6> SG6 { get; set; }

            [JsonProperty("SG7")]
            [XmlElement(ElementName = "SG7")]
            public List<SG7> SG7 { get; set; }

            [JsonProperty("SG8")]
            [XmlElement(ElementName = "SG8")]
            public List<SG8> SG8 { get; set; }

            [JsonProperty("SG9")]
            [XmlElement(ElementName = "SG9")]
            public List<SG9> SG9 { get; set; }

            [JsonProperty("SG12")]
            [XmlElement(ElementName = "SG12")]
            public List<SG12> SG12 { get; set; }

            [JsonProperty("SG14")]
            [XmlElement(ElementName = "SG14")]
            public List<SG14> SG14 { get; set; }

            [JsonProperty("SG16")]
            [XmlElement(ElementName = "SG16")]
            public List<SG16> SG16 { get; set; }

            [JsonProperty("SG24")]
            [XmlElement(ElementName = "SG24")]
            public SG24 SG24 { get; set; }

            [JsonProperty("SG26")]
            [XmlElement(ElementName = "SG26")]
            public List<SG26> SG26 { get; set; }

            [JsonProperty("UNS")]
            [XmlElement(ElementName = "UNS")]
            public UNS_Group UNS { get; set; }

           [JsonProperty("UNT")]
            [XmlElement(ElementName = "UNT")]
            public UNT UNT { get; set; }
        }

        #region UNB
        /// <summary>
        /// Message header
        /// </summary>
        [EdiSegment, EdiPath("UNB")]
        public class UNB
        {
            [JsonProperty("S001")]
            [XmlElement(ElementName = "S001")]
            public S001 S001 { get; set; }

            [JsonProperty("S002")]
            [XmlElement(ElementName = "S002")]
            public S002 S002 { get; set; }

            [JsonProperty("S003")]
            [XmlElement(ElementName = "S003")]
            public S003 S003 { get; set; }

            [JsonProperty("S004")]
            [XmlElement(ElementName = "S004")]
            public S004 S004 { get; set; }

            [EdiValue("9(99)", Path = "*/4/0")]
            [JsonProperty("E0020")]
            [XmlElement(ElementName = "E0020")]
            public string x_0020 { get; set; }

            [JsonProperty("S005")]
            [XmlElement(ElementName = "S005")]
            public S005 S005 { get; set; }

            [EdiValue("9(99)", Path = "*/6/0")]
            [JsonProperty("E0026")]
            [XmlElement(ElementName = "E0026")]
            public string x_0026 { get; set; }

            [EdiValue("9(99)", Path = "*/8/0")]
            [JsonProperty("E0029")]
            [XmlElement(ElementName = "E0029")]
            public string x_0029 { get; set; }

            [EdiValue("9(99)", Path = "*/9/0")]
            [JsonProperty("E0031")]
            [XmlElement(ElementName = "E0031")]
            public string x_0031 { get; set; }

            [EdiValue("9(99)", Path = "*/10/0")]
            [JsonProperty("E0032")]
            [XmlElement(ElementName = "E0032")]
            public string x_0032 { get; set; }

            [EdiValue("9(99)", Path = "*/11/0")]
            [JsonProperty("E0035")]
            [XmlElement(ElementName = "E0035")]
            public string x_0035 { get; set; }


        }

        [EdiElement, EdiPath("*/0")]
        public class S001
        {
            /// <summary>
            /// Message type
            /// </summary>
            [EdiValue("9(99)", Path = "*/*/0")]
            [JsonProperty("E0001")]
            [XmlElement(ElementName = "E0001")]
            public string x_0001 { get; set; }
            /// <summary>
            /// Message version number
            /// </summary>
            [EdiValue("9(99)", Path = "*/*/1")]
            [JsonProperty("E0002")]
            [XmlElement(ElementName = "E0002")]
            public string x_0002 { get; set; }
            
        }

        [EdiElement, EdiPath("*/1")]
        public class S002
        {
            [EdiValue("9(99)", Path = "*/*/0")]
            [JsonProperty("E0004")]
            [XmlElement(ElementName = "E0004")]
            public string x_0004 { get; set; }
      
            [EdiValue("9(99)", Path = "*/*/1")]
            [JsonProperty("E0007")]
            [XmlElement(ElementName = "E0007")]
            public string x_0007 { get; set; }
          
            [EdiValue("9(99)", Path = "*/*/2")]
            [JsonProperty("E0008")]
            [XmlElement(ElementName = "E0008")]
            public string x_0008 { get; set; }
        }

        [EdiElement, EdiPath("*/2")]
        public class S003
        {
            [EdiValue("9(99)", Path = "*/*/0")]
            [JsonProperty("E0010")]
            [XmlElement(ElementName = "E0010")]
            public string x_0010 { get; set; }

            [EdiValue("9(99)", Path = "*/*/1")]
            [JsonProperty("E0007")]
            [XmlElement(ElementName = "E0007")]
            public string x_0007 { get; set; }

            [EdiValue("9(99)", Path = "*/*/2")]
            [JsonProperty("E0014")]
            [XmlElement(ElementName = "E0014")]
            public string x_0014 { get; set; }
        }

        [EdiElement, EdiPath("*/3")]
        public class S004
        {
            [EdiValue("9(99)", Path = "*/*/0")]
            [JsonProperty("E0017")]
            [XmlElement(ElementName = "E0017")]
            public string x_0017 { get; set; }

            [EdiValue("9(99)", Path = "*/*/1")]
            [JsonProperty("E0019")]
            [XmlElement(ElementName = "E0019")]
            public string x_0019 { get; set; }

        }

        [EdiElement, EdiPath("*/5")]
        public class S005
        {
            [EdiValue("9(99)", Path = "*/*/0")]
            [JsonProperty("E0022")]
            [XmlElement(ElementName = "E0022")]
            public string x_0022 { get; set; }

            [EdiValue("9(99)", Path = "*/*/1")]
            [JsonProperty("E0025")]
            [XmlElement(ElementName = "E0025")]
            public string x_0025 { get; set; }
        }

        #endregion

**Comment by cleftheris** [comment]
Hi @GingerNinjaa the problem here is the placement of the **Interchange** structure header UNB inside of the logical structure **Message**

Take into account that in the EDI grammar the well known segments (the only ones that define non business structure) are as follows
```c#
"UNA"; // ServiceStringAdviceTag
"UNB"; // InterchangeHeaderTag 
  "UNG"; // FunctionalGroupHeaderTag (optional)
    "UNH"; // MessageHeaderTag
    "UNT"; // MessageTrailerTag
  "UNE"; // FunctionalGroupTrailerTag  (optional)
"UNZ"; //InterchangeTrailerTag
```

so what you need is a root class (no need to decoeate that with an edi attribute) that plays the role of the interchange structure. For convenience if the root type given to the `EDISerializer` for deserialization is decorated as Message it decides to ignore all outer structure and focus on the message.

**Comment by GingerNinjaa** [comment]
Hi,

I dont know if I understan it corectlyI need to create Clas UNB in "ROOT" in order to map this segment, but when I use [EdiMessage] Serializer/Deserializer will skip the rest? 

I try to do it as I understand, but then I only map UNB segment isted of all. Could you give me some sample class? 

![image](https://user-images.githubusercontent.com/49481082/141351469-e59e3d98-b81e-4574-92b8-dfdfe779267f.png)

**Comment by cleftheris** [comment]
No the above example you gave me before the screenshot had the UNB inside the message element. I did not mean that you needed to remove the EdiMessageAttribute. Your screenshot on the left seems to have a correct structure but you still need EdiMessage there the code sample on your first comment is different  (has UNB along with UNH inside a the message class).

**Comment by GingerNinjaa** [comment]
Hi,

Thank youi for your help this help me a lot.
