### ISSUE TITLE
BORD512, ENTL512 and STAT512? 

### ISSUE THREAD

**Issue by kvavoulis** [indice-co/EDI.Net#215]
hello clefteris
1. if I use your code I have to buy a licence? 
2. Have any code about BORD512, ENTL512 and STAT512? 

if you want send me private message for a project

**Comment by cleftheris** [comment]
Hi @kvavoulis the library is has MIT license which essentially means you can do whatever you like with it.

Unfortunately maintaining transmission models is outside of the scope of the library.

**Comment by kvavoulis** [comment]
have you know any solution to these prototypes. 
We search for a solution for EDI integration solution with our system 
EDI Fact and these new prototypes

**Comment by cleftheris** [comment]
Hi @kvavoulis,

regarding these transmissions and any other you need to consume or produce you will have to find a EDI specification document and and create a model class that can parse it. I googled and found one that is good for starting out https://active-edi.com/wp-content/uploads/2016/07/2011_07_active-logistics_Rel100_BORD512_EN.pdf

If you need something ready made you will have to check with another library/solution.

C.
