### ISSUE TITLE
Remove CR Carriage Return and LF Line feed

### ISSUE THREAD

**Issue by tomtom4848** [indice-co/EDI.Net#229]
Hi, 

I am working with EDI.Net for the first time and have a question:

in the example: 
`var grammar = EdiGrammar.NewTradacoms();
var interchange = new Interchange();
// fill properies 
interchange.TransmissionDate = DateTime.Now;
...
// serialize to file.
using (var textWriter = new StreamWriter(File.Open(@"c:\temp\out.edi", FileMode.Create))) {
    using (var ediWriter = new EdiTextWriter(textWriter, grammar)) { 
        new EdiSerializer().Serialize(ediWriter, interchange);
    }
}`

there is a Carriage Return and Line feed after every ' in the out.edi file... is it possible to write it in a file without CR,LF?

**Comment by cleftheris** [comment]
Hi @tomtom4848 you can set the Formatting property on the `EdiTextWriter` class to `Formatting.None` instead of the default which is line per segment

**Comment by tomtom4848** [comment]
That worked great! Thank's @cleftheris
