### ISSUE TITLE
EDIFACT Serialisation and UNT segment count

### ISSUE THREAD

**Issue by MBennetts** [indice-co/EDI.Net#239]
Hi - firstly thankyou for this library, it is excellent and pretty straightforward to use.

I have a query that I hope you can assist with related to serialisation of EDIFACT messages.

As you know the messages have a standard trailer segment (UNT) - can you tell me if there is a way for the EDI.Net library to
automatically determine the correct segment count and populate this segment or is this something I have to calculate myself?

Thanks

**Comment by MolACroes** [comment]
Use the decorator:

 `    [EdiCount(EdiCountScope.Segments)]`

**Comment by MBennetts** [comment]
Excellent - many thanks
