### ISSUE TITLE
How to omit unpopulated segment?

### ISSUE THREAD

**Issue by MikeCrutchfield** [indice-co/EDI.Net#242]
I am trying to omit the 'N2' segment from being written out to an 855 Document file.  There is no data for the segment but it writes the line anyway.

```
DTM*068*20230207~
N1*BT*Bill To Name~
N2*~
N3*Bill To Address~
N4*Bill City***US~
N1*ST*Jane Doe~
N2*~
N3*33 South Sixth Street~
N4*Minneapolis*MN*55402*US~
PO1*1*1*EA*32.92**VN*717NV2IC8A~
```

I have set the Mandatory attribute flag to false and not declared it at all without success.

```csharp
		[EdiValue(Path = "N2/0", Description = "N201 - Name", Mandatory = false)]
		public string AdditionalName { get; set; }

		[EdiValue(Path = "N2/0", Description = "N201 - Name")]
		public string AdditionalName { get; set; }
```

Thanks for any help.

**Comment by cleftheris** [comment]
Hi,
 
In order to omit the segment from your transmission you have to wrap it in a segment decorated class. After that if the property that holds the N1Segment is set to null the serializer will skip it completely. 

C.
