### ISSUE TITLE
How to defined my poco?

### ISSUE THREAD

**Issue by capqueen** [indice-co/EDI.Net#25]
I'm new to parse edi.I have a edi doc like below:
```
00:IFTMBF:BOOKING:9:XXXX:SINOTRANS:20090530:2.0'
02:XXXXBOOKING-0002:BLNO002:CY/CY::::::::::::SCNO'
03:1:CNSHA:SHANGHAI::3:CNSHA:CNSHA'
11::VESSEL:VOYAGE:SNL::SNL::20090630:::::'
12:CNCKG:CHONGQING:CNSHA:SHANGHAI:JPTYO:TOKYO:SGSIN:SINGAPORE:USNYC:NEW YORK:CNTAO:QINGDAO:'
14:PP: FREIGHT PREPAID'
15::FEEMEMO:PP:'
17:REMARK1:REMARK2:REMARK3:REMARK4:REMARK5'
18::SHNAME:SHADDR
TEL
FAX'
19::CONAME:COADDR
TEL
FAX'
20::NONAME:NOADDR
TEL
FAX'
21::NO2NAME'
40:40GP:1:L:XXXXBOOKING-0001::::Y:1::'
41:1:HSCODE:S:1:HYBG:BAG:2:3.000:2:HYBG:BAGS:3:4:8:9:J:JYN:100:2:CN'
43:CLS:PAGE:UNNO:LABEL:FP:EMS:MFAG:Y:EME:100:C:1:2:3:1:2:3:4:5:DANAME:DATEL:DAMAIL:DAFAX'
44:MARKS:::::'
47:CARGODESC:::::'
51:SNTU4014628:40GP:SEAL:E::F:1:8:9:3'
99:19'
```
I try NewEdiFact to deserialize, but get error, the document does not have a segment name '+'.
so what can i do? to defined a new EdiGrammar or maybe my pojo is not right?
can you please give me some suggestion, thank you very much

**Comment by cleftheris** [comment]
Hi @capqueen, this looks like EdiFact indeed and it is the __IFTMBF__ transmission (Firm booking message). But there is something weird going on. The EDI parser is complaining about two things 

1. the absence of segment names (UNH,CTX etx). 
2. there might be a slight deviation from the default grammar of EDIFact. The default `DataElementSeparator` `+` is nowhere to be found so it may be different. 

Is this a valid transmission? Take a look at [IFTMBF_EANCOM.pdf](http://www.gs1.org/sites/default/files/docs/eancom/s3/iftmbf.pdf)

**Comment by cleftheris** [comment]
Hi @capqueen did you manage to fix this. Sould I close the issue?

**Comment by capqueen** [comment]
Thanks a will check my edi text. yes u can close this issue. thank you very much
