### ISSUE TITLE
Can't Create object from class c506_2 that nested from class RFF_2 that nested from class RFFLoop1 that nested from class CNILoop1

### ISSUE THREAD

**Issue by hamed22222** [indice-co/EDI.Net#32]
```csharp
[EdiSegment,EdiPath("RFF")]
public partial class RFF_2
{

    private C506_2 c506_2Field;
    [EdiValue("X(10)", Path = "RFF/0")]
    public string hamed { get; set; }
    /// <remarks/>
    
     [EdiMessage]
    public C506_2 C506_2
    {
        get
        {
            return this.c506_2Field;
        }
        set
        {
            this.c506_2Field = value;
        }
    }
}
```

**Comment by cleftheris** [comment]
Hi @hamed22222 on a first look it seems that you have nested `EdiMessage` inside an `EdiSegment` class. This is not permitted. If you need a structure like that you will have to use `SegmentGroupAttribute` on the outter class and the segment & element attributes inside. You can check for an [example here](https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/Models/EdiFact01.cs). In order to help you out further I will need to see the code model that is failing along with the `sample.edi` file.

**Comment by gk7gk7** [comment]
[EFACT_D95B_CUSCAR.txt](https://github.com/indice-co/EDI.Net/files/790863/EFACT_D95B_CUSCAR.txt)

**Comment by gk7gk7** [comment]
@hamed22222 can you send us a sample EDI payload?

**Comment by hamed22222** [comment]
[Sample EDI.txt](https://github.com/indice-co/EDI.Net/files/792523/Sample.EDI.txt)

**Comment by hamed22222** [comment]
![untitled](https://cloud.githubusercontent.com/assets/25904506/23202352/41b10680-f8e6-11e6-8ccb-220837cdcd6a.png)
that's my problem class called (c506_2) doesn't generate instance

**Comment by cleftheris** [comment]
We will create a new test for this using the `SegmentGroupAttribute` and get back to you

**Comment by hamed22222** [comment]
Waiting for your Response ,thank u

**Comment by gk7gk7** [comment]
We made some of the mapping involved using your sample and your model. You can find it here:
[EdiFact_D95B_CUSCAR.cs](https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/Models/EdiFact_D95B_CUSCAR.cs)

I have also created a test case with the assertions. Off-course this is a huge transmission & we did not cover everything but you will get the point.

Just for the sake of completeness there are some rules not have inmind when mapping EDI transmissions to  CLR classes: 

> Classes that are decorated with `Segment`, `SegmentGroup`, `Message`, `Group` or `Interchange` consume the segment that defines the contrainer and cannot be reused inside them. If that makes sense you cannot have a Segment loop class `RffLoop` and an otherone inside `Rff` mapped to the same segment. The inner one will not map.


Regards
