### ISSUE TITLE
Properties getting instanciated but with no data

### ISSUE THREAD

**Issue by Nekeniehl** [indice-co/EDI.Net#38]
Hi there, following the structure
```
-NAD
   -COM
       -CTA
```
![2017-04-04_15-09-21](https://cloud.githubusercontent.com/assets/3227198/24856569/7ab561fa-1de5-11e7-8331-612343f15a23.png)

I have made:
```csharp
[EdiSegmentGroup("NAD")]
public class NAD
{
    [EdiValue("X(3)", Path = "NAD/0/0")]
    public string Qualifier { get; set; }

    [EdiValue("X(35)", Path = "NAD/1/0")]
    public string ID { get; set; }

    [EdiValue("X(3)", Path = "NAD/1/2")]
    public string Code { get; set; }

    public CTA CTA { get; set; }
}

[EdiSegmentGroup("CTA")]
public class CTA
{
    [EdiValue("X(3)")]
    [EdiPath("CTA/0/0")]
    public string Funktion { get; set; }

    [EdiValue("X(17)")]
    [EdiPath("CTA/1/0")]
    public string Kontaktnummer { get; set; }

    [EdiValue("X(255)")]
    [EdiPath("CTA/1/1")]
    public string Kontakt { get; set; }

    //public List<COM> Com { get; set; }

    [EdiCondition("TE", Path = "COM/0/1")]
    public COM TE { get; set; }

    [EdiCondition("EM", Path = "COM/0/1")]
    public COM EM { get; set; }
}

[EdiSegment]
[EdiPath("COM")]
public class COM
{
    [EdiValue("X(255)")]
    [EdiPath("COM/0/0")]
    public string Kommunikationsverbindung { get; set; }

    [EdiValue("X(3)")]
    [EdiPath("COM/0/1")]
    public string Art { get; set; }
}
```

The CTA is instantiated (both, TE and EM) but with no date inside. If I use instead the //commented property `List<COM> Com` everything gets serialised there. I guess is a wrong using of attributes?

I also realised that you use Byte for the Picture, in this example the field COM/0/0, "Kommunikationsverbiundung" can be up to 512 characters, which causes an exception, guess is not important on that field, but there are some others where the user can input free text (for example, to explain why a specific message is rejected).
![chrome_2017-04-10_12-06-34](https://cloud.githubusercontent.com/assets/3227198/24856847/6d52cd9e-1de6-11e7-93d9-34e9488aeda2.png)

I have made a pull request with the a cleaned ORDRSP class and the correct fixes for #36 including also a test for this scenario.
Hope you can help me. Thanks!

**Comment by cleftheris** [comment]
This is a known bug related to the condition attribute I am fixing. The workaround is to make use of the ElementAttribute instead of the Segment like so:

```csharp
[EdiElement]
[EdiPath("COM/0")]
public class COM
{
    [EdiValue("X(255)")]
    [EdiPath("COM/0/0")]
    public string Kommunikationsverbindung { get; set; }

    [EdiValue("X(3)")]
    [EdiPath("COM/0/1")]
    public string Art { get; set; }
}
```

**Comment by Nekeniehl** [comment]
Sadly it is not working that way neither. I will close this issue and wait for the bugfixing for the edicondition to test again. Thanks!
