### ISSUE TITLE
Compression in EDIFACT messages

### ISSUE THREAD

**Issue by KoosBusters** [indice-co/EDI.Net#48]
I believe the current serializer does not implement the EDIFACT specs on compression: https://web-beta.archive.org/web/20161004192113/www.unece.org/trade/untdid/texts/d422_d.htm#p7

The sample edifact.01.edn message contains the following line [(here)](https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/Samples/edifact.01.edi#L2)
`UNB+UNOC:3+1234567891123:14+7080005059275:14:SPOTMARKED+101012:1104+HBQ001++++1'`

The unit test expected value has an extra ':' behind the 14, creating an ':+' combination [(here)](https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/SerializerTests.cs#L26)
`UNB+UNOC:3+1234567891123:14:+7080005059275:14:SPOTMARKED+101012:1104+HBQ001++++1'`

I believe the specs describe that the : should be omitted.

I will see if I can change this behavior and create an PR

**Comment by KoosBusters** [comment]
I have made some changes to the serializer that fix this issue for all of my message implementations: https://github.com/KoosBusters/EDI.Net/commit/63ba14f73885f2a95a88bce81274588dab875023

All unit tests are still ok, but I think this behavior should be behind an configuration boolean because it might cause side effects if all messages are suddenly compressing. Maybe it should be part of the grammar in a way because it's the EDIFACT specs that require the compression?

@cleftheris it couldn't really find the place where to put in the current structure of the serializer, as a result it feels a bit as an add-on to the ediwriter instead of being an integral part of it. Could you have a look at this and see if there is a better way?

**Comment by cleftheris** [comment]
I agree it should be part of some kind of settings. Not sure it belong to the grammar though.
I think I prefer the commit.

**Comment by cleftheris** [comment]
@KoosBusters I tried to leave comments on the commit itself. Have not done this before though. Did you get the feedback? https://github.com/KoosBusters/EDI.Net/commit/63ba14f73885f2a95a88bce81274588dab875023

**Comment by KoosBusters** [comment]
@cleftheris I can see a total of 3 comments on this commits. I will respond inline and see how that works :)

**Comment by KoosBusters** [comment]
@cleftheris I left some comments in the commit as well. Could you take a look if you find some time? I will correct everything and update the PR with another commit. Resharper now follows the editorconfig after updating it to the latest version.

**Comment by cleftheris** [comment]
@KoosBusters I will try to find some time this week and close this.

**Comment by KoosBusters** [comment]
Thanks!

**Comment by KoosBusters** [comment]
Hi @cleftheris ,
I working on other projects the past few weeks but I'm about to get working on this again.

Any updates on this?
