### ISSUE TITLE
EDI x12 856 support

### ISSUE THREAD

**Issue by lemessur** [indice-co/EDI.Net#51]
I'm working on adding support for x12 856 files. The problem I'm running into is that the standard seems to support multiple orders per shipment, but there is no guarantee of a distinguishing tag at the beginning/end of an order section. The HL tag is used extensively inside of shipments, orders and packs. In other words it's not unique any particular block type. I think the Condition marker might be my solution, but I'm still figuring out how to use it.

Has anyone tried implementing 856 support/have any ideas about this?

The spec I'm using as a reference is here:
http://www.gentex.com/sites/default/files/EDI%20856%20(Advanced%20Ship%20Notice)%20Specification%20Document.pdf

**Comment by gk7gk7** [comment]
@lemessur in every EDI implementation one of the first things a user needs to identify is the structure of the messages. The structure helps the user to understand the way to build the objects that will facilitate the data. The spec you are working with indicates a structure. 
```
BSN*00*72052*20120517*0956!	<--Header							
ST*856*0001!		        <--Header		
DTM*011*20120517*0956!		<--Header							
DTM*017*20120518*1130!		<--Header								
HL*1**S!		 <--Shipment Level Details
MEA*PD*G*100*LB!	 <--Shipment Level Details
MEA*PD*N*99*LB!		 <--Shipment Level Details
REF*PK*72052!		 <--Shipment Level Details
REF*BM*117981!		 <--Shipment Level Details
N1*ST**92*CEN!		 <--Shipment Level Details	
N1*SU**92*14302-DIRECT!	 <--Shipment Level Details
HL*2*1*I!				<--Item Level Details
LIN**BP*345-0880-000*EC*BAC!	        <--Item Level Details
SN1**288*EA!				<--Item Level Details
PRF*1332538****1!			<--Item Level Details
CTT*1*288!			<--Summary
SE*16*0001!			<--Summary									
```
the first time, you find a HL element it will most likely be for the Shipment Level Details. Per the spec (page 8 - last line) the 3rd element (**S**) is the type identifier for this HL segment on which the condition can be applied. In addition, the spec indicates that this HL must be used only 1 time. So, the next time you find another HL element it will be for the Item Level Details. Per the spec (page 12 - last line) the 3rd element (**I**) is the type identifier for this the Item Level Detail -HL- segment. Additionally, the 2nd element indicates the Parent of this child.

I hope I was helpful enough to make you understand how to build your models.

**Comment by lemessur** [comment]
Thanks. I've got the parser extracting nearly all of the necessary information. When I have time I'll clean it up a bit, make it more generic and submit a pull request with the new 856 interface. It's a common enough format that someone might find it useful.

**Comment by solexsylvain** [comment]
Hi @lemessur , did you end up finishing 856 ? If so, can you please upload it ? I just completed a format for 855 that looks fine.

**Comment by lemessur** [comment]
Unfortunately, no. Other things took priority and now I have a different
job.

**Comment by solexsylvain** [comment]
that's life. enjoy the new job.

**Comment by edeharo** [comment]
Hi, I am looking the 856 too, @solexsylvain, did you build it ? If so, can you shared it ?

**Comment by solexsylvain** [comment]
Hi,

 

I’m still working on it, once the integration is done either today or tomorrow, I could send it to your email if you still want it.

 

I’ll be too busy for the next few weeks, If you want to improve the quality of it and upload it to the project, feel free.  

 

Sylvain Cyr

Directeur des technologies et solutions

Director of Technology & Solutions
