### ISSUE TITLE
Whitespace ignored at start of component

### ISSUE THREAD

**Issue by KoosBusters** [indice-co/EDI.Net#52]
The EDIFACT CUSCAR spec splits the FTX-TEXT LITERAL segment up in 5 components of max 70 characters. A split can happen right before a space but the current implementation will remove the first whitespace for all components.

Removing the skipping over whitespace in the EdiTextReader seems to fix this issue without any side-effects (all unit tests, included and my own implementation unit tests, are still successful after the change), but I'm not sure what specification caused the skip to be implemented in the first place, so I cannot verify this scenario.

**Comment by cleftheris** [comment]
There is no specification involved just me deserializing into business objects and trimming legacy systems' fixed length text. If you can send me a PR I can push a release for this.

**Comment by KoosBusters** [comment]
PR should be in as #53. Thanks!
