### ISSUE TITLE
Reading multiple reference from line item

### ISSUE THREAD

**Issue by matejgolob** [indice-co/EDI.Net#54]
Hi. I need help.  I want to "enhance" your example (Edifact_ORDRSPTests) with parsing more details from example edi file edifact.ORDRSP. I would like to read references from line-items in this example:
RFF+Z09:8465929523'
RFF+Z06:7'

I have added class:
`    [EdiSegment]
    [EdiPath("RFF")]
    public class MyRff
    {
        [EdiValue("X(70)", Path = "RFF/0/1")]
        public string Code { get; set; }

        [EdiValue("X(3)", Path = "RFF/0/0")]
        public string Qualifier { get; set; }
    }`

and then inside LineItem class:
 `        [EdiCondition("Z09", Path = "RFF/0")]
        public MyRff ReferenceZ09 { get; set; }

        [EdiCondition("Z06", Path = "RFF/0")]
        public MyRff ReferenceZ06 { get; set; }`

But data is not parsed into LineItem class. What am I doing wrong?

Thanks for help.

Matej Golob

**Comment by Nekeniehl** [comment]
Hi there,

Please try decorating the MyRff class like the following:
```
[EdiSegmentGroup("RFF[0][0]", SequenceEnd = "AJT[0][0]")]
public class RFF
{
	private string _id;

	private string _code;

	[EdiValue("X(70)", Path = "RFF/0/0")]
	public string ID
	{
		get
		{
			return this._id;
		}
		set
		{
			this._id = value;
		}
	}

	[EdiValue("X(3)", Path = "RFF/0/1")]
	public string Code
	{
		get
		{
			return this._code;
		}
		set
		{
			this._code = value;
		}
	}
}
```

**Comment by cleftheris** [comment]
Hi @matejgolob  can we close this issue as resolved?

**Comment by matejgolob** [comment]
Yes it can be closed. Sorry for late response and thanks for help.
