### ISSUE TITLE
Omitting blank segments when serializing?

### ISSUE THREAD

**Issue by kharlamov** [indice-co/EDI.Net#55]
Hello all, I have a rather simple question, my model has some segments that are optional for example in this example (N3, N4) are optional address information segments:

```
...
DTP***20110201~
N3**~
N4****~
SE*50*~
...
```

Is there a way to make the serializer ignore these when generating my file or is this something I would have to do on my own? 

Here is an example of the output I would be going for:
```
...
DTP***20110201~
SE*50*~
...
```

**Comment by cleftheris** [comment]
Hi @kharlamov this is something that is not currently supported. Although, it could be possible through the `EdiSerializer`.

**Comment by michaelachrisco** [comment]
@kharlamov  did you ever fix this? I am having the same issue with some REF Segments:
```
REF*38*111111111*~
```

Looking over the `EdiSerializer` ATM.

**Comment by michaelachrisco** [comment]
If anyone comes across this error here is how I fixed it with some X12 834/835/227/etc... files (From unit test):
```c#
            string myString = "";
            string pattern = @"\b\*+\~";
            Regex rgx = new Regex(pattern);
 
            MockFileData TestFile = new MockFileData("");
            string FilePath = @"C\\test.edi";
            EdiSerializer ediSerializer = new EdiSerializer();
            // serialize to file.
            //TODO: Test serialization of file.
            using (var stream = new MemoryStream())
            {
                using (var textWriter = new StreamWriter(stream))
                {
                    stream.Position = 0;
                    using (var ediWriter = new EdiTextWriter(textWriter, grammar))
                    {
                        ediSerializer.Serialize(ediWriter, interchange);
                    }
                    string UnformattedEDI = System.Text.Encoding.Default.GetString(stream.ToArray());
                    //\b\*+\~
                    myString = rgx.Replace(UnformattedEDI, "~");
                }
            }
            Assert.AreEqual(Test834Contents, myString);
```

Its not the most ideal solution but it looks for all instances of any number of the X12 separator`*` and ~ then replaces them with just the line delimiter. 

Example record with bunk data on 834 EDI:
```
Before: INS*Y*18*030*XN*A*E**AC*F**D8*20180101*****~
After: INS*Y*18*030*XN*A*E**AC*F**D8*20180101~
```

**Comment by cleftheris** [comment]
Supported as of  release v1.7.0

**Comment by ducksauce88** [comment]
I do not see any documentation on how to omit an empty segment when serializing. How do I do this? I'm currently looking through the v1.7.0 release commits and I'm not familiar with this code. I assume its something configurable in the EdiSerializer
