### ISSUE TITLE
Reading multiple element from line item

### ISSUE THREAD

**Issue by rkotulan** [indice-co/EDI.Net#56]
Hi,

on my ORDRSP I have multiple elements
QTY+113:26:PCE'
DTM+67:20170607:102'
QTY+113:24:PCE'
DTM+67:20170609:102'

How can I read this?

Thanks, best regards,
Rudolf

**Comment by cleftheris** [comment]
I suppose you mean multiple repeating segments. This could be handled as a Loop with the `SegmentGroupAttribute`. Check the tests there is an example for this

**Comment by rkotulan** [comment]
Could you please point me to specific test. I did not find it.

**Comment by cleftheris** [comment]
I believe in this [model](https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/Models/EdiFact01.cs) that parses this [sample](https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/Samples/edifact.01.edi) you can see how to handle segment groups

**Comment by rkotulan** [comment]
Thanks a lot.
