### ISSUE TITLE
EdiElements inside EdiSegments

### ISSUE THREAD

**Issue by Nekeniehl** [indice-co/EDI.Net#59]
Hi there, 

I'm having troubles again with some EdiElements, I don' t really understand what is going on and maybe someone can give me some light here because I'm really blocked at this point and start thinking that is better to directly avoid this structure and do it without EdiElements

I have a EdiSegment, with some EdiValues and some EdiElements (CXXX) in both classes, one definition for the RFF Segment and another one for the NAD Segment.

For the NAD Segment is working, but not for the RFF

```csharp
[EdiElement]
public class C506
{
    #region Properties

    [EdiValue("X(3)", Path = "RFF[0][0]")]
    public string Reference_Code_Qualifier { get; set; }

    [EdiValue("X(70)", Path = "RFF[0][1]")]
    public string Reference_ID { get; set; }

    [EdiValue("X(6)", Path = "RFF[0][2]")]
    public string Document_Line_ID { get; set; }

    [EdiValue("X(9)", Path = "RFF[0][3]")]
    public string Version_ID { get; set; }

    [EdiValue("X(6)", Path = "RFF[0][4]")]
    public string Revision_ID { get; set; }

    #endregion
}

[EdiSegment]
[EdiPath("RFF/0/0")]
public class RFF
{
    [EdiPath("RFF/0/0")]
    public C506 C506 { get; set; }
}

[EdiElement]
public class C082
{
    #region Properties

    [EdiValue("X(35)", Path = "NAD[1][0]")]
    public string Party_ID { get; set; }

    [EdiValue("X(17)", Path = "NAD[1][1]")]
    public string Codelist_ID { get; set; }

    [EdiValue("X(3)", Path = "NAD[1][2]")]
    public string Codelist_Resp_Agency { get; set; }

    #endregion
}

[EdiPath("NAD/0/0")]
[EdiSegment]
public class NAD
{
    #region Properties

    [EdiValue("X(3)", Path = "NAD[0][0]")]
    public string Party_Function_Code_Qualifier { get; set; }

    [EdiPath("NAD/1/0")]
    public C082 C082 { get; set; }

    [EdiValue("X(35)", Path = "NAD[5][0]")]
    public string City_Name { get; set; }

    [EdiValue("X(17)", Path = "NAD[7][0]")]
    public string Postal_ID { get; set; }

    [EdiValue("X(3)", Path = "NAD[7][1]")]
    public string Country_ID { get; set; }

    #endregion
}
```

I guess the problem is located in EdiTypeDescriptor and EdiPropertyDescriptor, but I'm not sure, hope you can help me, Thanks in advance!

**Comment by cleftheris** [comment]
Hi @Nekeniehl

sorry it has been a while! There was a major rewrite to the deserializer since version 1.7 and I was wondering if you can confirm this issue is resolved. 

There is a good example of nesting is test case with EDIFact_D01B_IFCSUM here: https://github.com/indice-co/EDI.Net/blob/87d392aa6a49340eccdf5af7b72df85d7b1daa07/test/indice.Edi.Tests/EdiTextReaderTests.cs#L832 

The models are quite good for this sample so it is worth checking it out.

Regards

**Comment by cleftheris** [comment]
Closing as not active. Also I am pretty sure the case was valid when opened but since v1.7 this should be covered.
