### ISSUE TITLE
X12 Serializer Do not serialize NULL properties?

### ISSUE THREAD

**Issue by vladdara** [indice-co/EDI.Net#60]
Hi,
If I have a class with several properties(which represents a segment and corresponding elements), there is a possibility to NOT serialize X12 properties which are NULL?
Thank you.

**Comment by cleftheris** [comment]
Hi @vladdara,
this is something called compression that I have not implemented yet on the `EdiTextWriter` class. There is an open ticket with a pull request related to this #48 and #55
