### ISSUE TITLE
where can I find sample test appication

### ISSUE THREAD

**Issue by kelumKP** [indice-co/EDI.Net#61]
please mention where can I find sample running application with this EDI.NET

**Comment by cleftheris** [comment]
The tests project serves as a sample application. What are you looking for exactly?
Also please check my answer to #62

**Comment by kelumKP** [comment]
I loaded the project to solution explorer  [http://i.imgur.com/2fBw1i9.png](url) as following and marked "indice.Edi.Tests" as Startup Project 

then I run that application, then I got command line window,  shortly after that, that window closed, once I checked "output" window in visual studio, I able to see something like this 
[http://i.imgur.com/Iaaurgv.png](url)

**Comment by cleftheris** [comment]
Hi this is not how test projects with unit tests work. You should be using the **test explorer window**,
![screenshot 2 _li](https://user-images.githubusercontent.com/1777633/28667704-4e99aece-72d5-11e7-8ed9-cc1815dcf0c2.jpg)

**Comment by kelumKP** [comment]
okay those are working like unit test project, where can I find GUI sample application for this ? 
if this doesn't contains any project like that, I want to develop demo application(as MVC or  Console Application), if so where should I start ?

**Comment by cleftheris** [comment]
I don't know what to suggest here. There could be numerous implementations I can think of but you are out of context here because this is a `Serializer` library and not tied to a specific GUI experience.

**Comment by kelumKP** [comment]
seems I unable to explain the my requirement properly, actually I want to build EDI application with the assist of EDI.NET , better if its a .Net Core application or asp.net MVC application

**Comment by cleftheris** [comment]
I would try File new .NetCore Web Application project (Api)
and then checkout how to hook the Serializer using Input and output formatters (https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-formatters)

But as I stated before it is out of the scope of this project.

**Comment by kelumKP** [comment]
Actually I'm trying to develop a UI like this 

[First Page](https://secure.edidev.net/edidev-ca/samples/vbWebGen810/) - A Form with a button to generate the EDI file

[Second Page](https://secure.edidev.net/edidev-ca/samples/vbWebTran810/) - two text areas with a button to that Translate EDI file to Human Readable File 

I can't imagine how its going to out of scope, just trying to do using user interface instead Xunit unit testing
