### ISSUE TITLE
System.ArgumentOutOfRange

### ISSUE THREAD

**Issue by chr12345** [indice-co/EDI.Net#63]
Why do I get an ArgumentOutOfRangeException by deserializing a Samplefile?

**Comment by cleftheris** [comment]
Hi, 

your question must be a little more specific. Post the sample file as well as a code sample you are using to parse this.

**Comment by HamiltonManalo** [comment]
Hello,

When doing my initial testing with the code I used [this file ](https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/Samples/edifact.01.edi)(as it most closely matches the EDI configuration that I will be decoding) and I also ran into the Argument out of range. I was able to parse it by removing the first line "﻿UNA:+.? '"

**Comment by cleftheris** [comment]
Closing this as most probable cause for the error is inconsistent transmission with grammar.
