### ISSUE TITLE
Deserialization of very large Edifact files

### ISSUE THREAD

**Issue by mvalero** [indice-co/EDI.Net#64]
Hello,

I would like to read large Edifact files containing several messages item by item instead of directly loading all the items into memory.

Is this supported by EDI.Net in any way?

Thanks

**Comment by cleftheris** [comment]
I would say that this should be possible if you are using a file stream as the library is gradually progressing through the transmission while deserializing. What is the problem you are encountering? 

```csharp
var grammar = EdiGrammar.NewEdiFact();
var interchange = default(MyInterchangeClass);
using (var stream = new StreamReader(@"c:\temp\sample.edi")) {
    interchange = new EdiSerializer().Deserialize<MyInterchangeClass>(stream, grammar);
}
```

**Comment by mvalero** [comment]
Thanks for the answer.

If I declare MyInterchangeClass in a way that it includes a list of messages as a property, the serializer reads the complete file and loads all serialized messages in that collection. I want to avoid doing that as some files could be really large and include lots of messages.

On the other way, if I declare MyInterchangeClass so it only declares the fields of one of my internal messages, the whole file is gonna be read anyway until the end, and the returned object will contain the last of the messages in the file.

Ideal would to be able to read one message at a time, with only the currently read message bein loaded into memory.

Am I missing something?

**Comment by cleftheris** [comment]
Aha! 
you should be able to cherry pick the meessages you want using the the `EdiConditionAttribute` on multiple list of messages properties on the same `MyInterchangeClass` as is the case with the example in the [here](https://github.com/indice-co/EDI.Net#model). Check how there are three classes decorated with the `[EdiMessage]` attribute.

Your next issue would be how to `break` the reading process upon certain criteria. This means that you need to override the default `EdiTextReader` with a custom one (`CustomEdiTextReader`) that you will then need to pass on to the deserialze method like so.

```csharp
var grammar = EdiGrammar.NewEdiFact();
var interchange = default(MyInterchangeClass);
using (var reader= new StreamReader(@"c:\temp\sample.edi")) {
    interchange = new EdiSerializer().Deserialize(new CustomEdiTextReader(reader, grammar), typeof(MyInterchangeClass));
}
```

what do you think?

**Comment by cleftheris** [comment]
@mvalero did you overcome your problem? Can I close this

**Comment by mvalero** [comment]
Hello @cleftheris, thank you for your help, I did overcame the problem.
