### ISSUE TITLE
Segement group inside segment group

### ISSUE THREAD

**Issue by erikkle** [indice-co/EDI.Net#69]
Hi,
Im having issues with trying to add the edifact MOA segment group inside LIN.

![image](https://user-images.githubusercontent.com/30823835/31806330-3f8126ae-b567-11e7-8aff-fcd192cf34c1.png)

LIN looks like this 

![image](https://user-images.githubusercontent.com/30823835/31806458-44776fbe-b568-11e7-9227-c324c6c660fa.png)

and MOA looks like this. I do not know what Edi attributes to put on MOA, i think i have tried them all.

![image](https://user-images.githubusercontent.com/30823835/31806467-55871f5c-b568-11e7-85b3-016693a2c21e.png)

Is there somewhere to get a fully functional edifact interchange classes, working for ORDERS, ORDRSP and INVOIC? The testmodels in this repo is not complete enough.

**Comment by cleftheris** [comment]
Hi @erikkle

Sorry I did not find the time to reply to your query. I am glad you made it work!
