### ISSUE TITLE
Serializer

### ISSUE THREAD

**Issue by updansharpe** [indice-co/EDI.Net#7]
is this library still being worked on, and is there a time scale for the serializer part of this? our client has a requirement to send out EDI files in tradacoms format and this would save us a lot of time/effort

**Comment by cleftheris** [comment]
Hi @updansharpe. thanks for your interest in `EDI.Net`.

Although the library is not my number one priority at the moment I am planning on a serializer at some point in the 2nd quarter of 2016. 

I Would be very grateful for any contribution though

**Comment by cleftheris** [comment]
As of `v1.1.0-beta` there is a test available with sample usage of the EdiWriter class. It can be found here: [WriterWritesStructureTest](https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/EdiTextWriterTests.cs)

It is in progress

**Comment by cleftheris** [comment]
closes with version 1.1.0
