### ISSUE TITLE
Deserializing SegmentGroup get's only a single Entry

### ISSUE THREAD

**Issue by Kirides** [indice-co/EDI.Net#71]
Iftmin: https://pastebin.com/TwGTHXZL
Classes: https://pastebin.com/SPY5EDLe

I try to Deserialize a NAD (SegmentGroup) which contains a CTA (Segment) and Nx COM (Segment).

While i Deserialize it as SegmentGroup, i only get the last occurrence of the desired NAD-SegmentGroup, which also contains information that belongs to another NAD-SegmentGroup.

![Deserialized](https://i.imgur.com/XM0hDCy.png)
```
[EdiMessage]
public class IftIssue
{
    public List<NAD> NADs { get; set; }

    [EdiSegmentGroup("NAD")]
    public class NAD
    {
       // Other code omitted

        public CTA Kontakt { get; set; }

        [EdiCondition("TE", Path = "COM/0/1")]
        public COM Telefon { get; set; }

        [EdiCondition("EM", Path = "COM/0/1")]
        public COM Email { get; set; }
    }


    [EdiSegment, EdiPath("COM/0/0")]
    public class COM
    {
        [EdiValue("X(512)", Mandatory = true, Path = "COM/0/0")]
        public string CommunicationAddressIdentifier { get; set; }

        [EdiValue("X(3)", Mandatory = true, Path = "COM/0/1")]
        public string CommunicationAddressCodeQualifier { get; set; }
    }

    [EdiSegment, EdiPath("CTA/0/0")]
    public class CTA
    {
        [EdiValue("X(3)", Path = "CTA/0")]
        public string ContactFunctionCode { get; set; }

        [EdiValue("X(17)", Path = "CTA/1/0")]
        public string DepartmentEmployeeNameCode { get; set; }

        [EdiValue("X(35)", Path = "CTA/1/1")]
        public string DepartmentEmployeeName { get; set; }
    }
}```

Once i Deserialize it as NAD-Segment i get all 3 NADs, but without the CTA/COM information.

Is my usage of "EdiSegmentGroup" wrong?

**Comment by Nekeniehl** [comment]
Hi,
I'm not sure if this will work, but I think you are missing the end sequence on the NAD, try the following, where "GID" is the first segment which is outside of your segment group.
    
```
[EdiSegmentGroup("NAD", SequenceEnd = "GID")]
public class NAD
{
   // Other code omitted

    public CTA Kontakt { get; set; }

    [EdiCondition("TE", Path = "COM/0/1")]
    public COM Telefon { get; set; }

    [EdiCondition("EM", Path = "COM/0/1")]
    public COM Email { get; set; }
}
```

**Comment by gk7gk7** [comment]
@Kirides I cannot reproduce what you show in your picture. The models (from pastebin) you used to deserialize the edi file, looks fine.

![debug-edi](https://user-images.githubusercontent.com/19185778/32376053-56090c2a-c0ac-11e7-864e-19a591ade75a.JPG)

**Comment by Kirides** [comment]
I cannot reproduce it either, using the latest release. (Idk which version the company used earlier)

Still, thanks alot. (Hate it when ppl do not tell you they use outdated source / "adjusted source")

**Comment by cleftheris** [comment]
@Kirides glad you sorted it out!
