### ISSUE TITLE
Serializing an object results in a non deserializable string

### ISSUE THREAD

**Issue by Kirides** [indice-co/EDI.Net#73]
Once i serialize my object i receive this kind of output:  
https://pastebin.com/UBqDnZsf

Now when i try to use this result, the deserializer will throw an exception because there is no segment terminator after the last segment.

```
indice.Edi.EdiReaderException: Unterminated string. Expected delimiter. Path 'UNZ[1][0]', line 1, position 1134.
```

Adding the terminator manually fixes this issue, but appending to the stream should not be needed, imo.

**Comment by cleftheris** [comment]
Hi @Kirides can you please give me a sample input file as well as Model for this. I can not reproduce the issue without one.

**Comment by Kirides** [comment]
Sadly, i can't anymore, lost the Sample and my company bought a service to handle EDIFACT Fileoperations
