### ISSUE TITLE
Can EDI.Net parse custom non-standard EDI-style files?

### ISSUE THREAD

**Issue by quartilesoftware** [indice-co/EDI.Net#77]
I have a custom format CSV file which is in the style of an EDI file, but the file is not one of the recognised standard EDI formats 
(Tradacoms, X12 or Edifact). The file is in a custom in-house EDI-style used by a very large wholesaler.

Can EDI.Net be used to read and parse such a file?

**Comment by cleftheris** [comment]
It depends on how much it resemples an EDI structure like the ones we use. Theoreticly speaking if you can map the basic structure of an interchange with messages to tags of a custom `EdiGrammar` then yes it could work.

**Comment by quartilesoftware** [comment]
Thanks. It's a very simple message structure - each row begins with a three-letter identifier to indicate: beginning of message; record header; record detail row(s); record trailer; end of message (MSG; HDR; DTL;TRL;END respectively). A typical file containing one message with two records with one and two detail rows might look like this:

MSG, MyTestCo,DateAndTimeString,LocationIdentifer,TypeOfMesage
HDR, <alphabetic, integer, decimal and date values separated by commas>
DTL, <alphabetic, integer, decimal and date values separated by commas>
TRL record rowcount,identifier 
HDR, <alphabetic, integer, decimal and date values separated by commas>
DTL, <alphabetic, integer, decimal and date values separated by commas>
DTL, <alphabetic, integer, decimal and date values separated by commas>
TRL, record rowcount,identifier
END, message recordcount,identifier

**Comment by gk7gk7** [comment]
Here is a custom Grammar and Custom Data style

Sample Data

>IHT,ANA:1,:ANY SHOP PLC,:XYZ MANUFACTURING PLC,940321,REFS,REFR_
>MSG,1,ORDHDR:9_
>TYP,0430,NEW-ORDERS_
>SDT,5000100001014:7215,XYZ MANUFACTURING PLC,LEEDS_
>CDT,5000600003101:68100,ANY SHOP PLC,HEAD OFFICE:72 KING STREET:LONDON EC2_
>FIL,1,1,940321_
>END,6_
>MSG,2,ORDERS:9_
>CLO,5000600003240::68322_
>ORD,981::940321_
>DIN,940328,,,RING BEFORE DELIVERY_
>DTL,1,5000100481452,5000100074326,,12,10,,,,PRODUCT A_
>DTL,2,5000100350666,5000100068271,,6,10,,,,PRODUCT B_
>DTL,3,5000100154073,5000100154066,,4,30,,,,PRODUCT C_
>OTR,3,6_
>END,9_
>MSG,3,ORDERS:9_
>CLO,5000600003282::68347_
>ORD,982::940321_
>DTL,1,5000100769680,5000100769673,,6,5,,,,PRODUCT K_
>DTL,2,5000100658465,5000100668136,,6,8,,,,PRODUCT L_
>OTR,2,13_
>END,7_
>MSG,4,ORDTLR:9_
>OFT,2_
>END,3_
>ITT,4_


Sample Grammar
```csharp
public class CustomGrammar : EdiGrammar
{
        
    public CustomGrammar() : base() 
    {
            _SegmentNameDelimiter = ',';
            _ComponentDataElementSeparator = ':';
            _DataElementSeparator = ',';
            _DecimalMark = null;
            _ReleaseCharacter = '?';
            _Reserved = new[] { ' ' };
            _SegmentTerminator = '_';
            _ServiceStringAdviceTag = null;
            _InterchangeHeaderTag = "IHT";
            _FunctionalGroupHeaderTag = "GHT";
            _MessageHeaderTag = "MSG";
            _MessageTrailerTag = "END";
            _FunctionalGroupTrailerTag = "GTT";
            _InterchangeTrailerTag = "ITT";
    }
}
```

Usually here is the tricky part, to do the correct mapping to your custom models

Sample model
```csharp
public class CustomInterchange
{
           [Serialization.EdiValue("X(14)", Path = "IHT/0/0")]
            public string InterchangeHeaderDataA { get; set; }

            public Message[] Messages { get; set; }
}
[EdiMessage]
public class Message
{
            [Serialization.EdiValue("9(1)", Path = "MSG/0/0")]
            public int MessageHeaderDataA { get; set; }

            [Serialization.EdiValue("X(14)", Path = "MSG/1/0")]
            public string MessageHeaderDataB { get; set; }

            [Serialization.EdiValue("9(1)", Path = "MSG/1/1")]
            public int MessageHeaderDataC { get; set; }


            [Serialization.EdiValue("9(1)", Path = "DTL/0/0")]
            public int MessageDataProp1 { get; set; }


            [Serialization.EdiValue("X(14)", Path = "DTL/1/0")]
            public string MessageDataProp2 { get; set; }
}
```


Then use both Grammar and InterchangeModel to see the result.
```csharp
public void NewGrammar_Test() {
       var grammar = new CustomGrammar();
       var interchange = default(CustomInterchange);
       using (var stream = Helpers.GetResourceStream("xxx-file-with-data.csv")) {
           interchange = new EdiSerializer().Deserialize<CustomInterchange>(new StreamReader(stream), grammar);
       }
       Assert.Equal(interchange.Messages.Length, 4);
}
```

I hope that gives a direction of how to start building both Grammar & Business Models.

**Comment by quartilesoftware** [comment]
Thanks very much.
