### ISSUE TITLE
Reading nested Data

### ISSUE THREAD

**Issue by HamiltonManalo** [indice-co/EDI.Net#78]
Hello!

Thank you for your amazing work. EDI.NET fits a hard to find criteria for parsing files. I've run into an issue and I can't seem to make any progress on it. The following nested data needs to be grouped together:

LIN+2++<EAN_2>:EN'
PIA+1+<VENDOR_SKU2>:SA'
MOA+36E:4868.5'
QTY+145:195'
QTY+21:0'
QTY+153:65'
LIN+3++<EAN_3>:EN'
PIA+1+<VENDOR_SKU3>:SA'
MOA+36E:0'
QTY+145:1' //Stock on hand (145): Qty (1)
QTY+21:0'  //Stock on order (21): Qty (0)
QTY+153:0' //Units Sold (153): Qty (0)

The structure I'm trying to achieve is 

LineItems (Some fields not noted)
-NumberIdentification
--NumberIdentification
-Prices
--Price
---Amount
---Code
-QTY
--QTY1
--QTY2
--QTY3
They're broken up by classes as follows

This class is functioning mostly as expected - But the Quantities field is not instantiating
``` 
    [EdiSegment, EdiSegmentGroup("PIA", SequenceEnd = "UNT")]
    public class LineItem
    {
        [EdiValue("X(1)", Path = "LIN/0")]
        public int LineNumber { get; set; }

        [EdiValue("9(3)", Path = "LIN1/0")]
        public string Code { get; set; }
        
        public ItemNumber NumberIdentification { get; set; }


        public Quantities Quantities { get; set; }

        public Period Period { get; set; }

        public List<PriceDetails> Prices { get; set; }
    }
```

This is functionig mostly as expected  with the exception of "Type" not picking up the last component but I think that is just user error. 

```
[EdiElement, EdiPath("PIA/1")]
    public class ItemNumber
    {
        [EdiValue("X(1)", Path = "PIA/1/0")]
        public string Number { get; set; }

        [EdiValue("X(3)", Path = "PIA/1/1")]
        public string Type { get; set; }

        [EdiValue("9(3)", Path = "LIN/2/2")]
        public string CodeListQualifier { get; set; }

        [EdiValue("9(3)", Path = "LIN/2/3")]
        public string CodeListResponsibleAgency { get; set; }

        public override string ToString()
        {
            return $"{Number} {Type} {CodeListQualifier}";
        }
    }
```

This is the part I have not been able to pull unique values with. So far the most functionality i've been able to get out of it is by running the class outside of the "report" file class and its only picking up "12" values (with conditions as shown here it is not picking up any details). 
```
    [EdiCondition("145","12","153", CheckFor = EdiConditionCheckType.Equal, Path = "QTY/0")]
    [EdiSegmentGroup("QTY", SequenceEnd = "UNT", Start = "MOA")]
    public class Quantities
    {
        //[EdiValue(Path = "QTY/0/1")]
        [EdiCondition("145", Path = "QTY/0/1")]
        public int Quantity1 { get; set; }

        [EdiCondition("12", Path = "QTY/0/1")]
        public int Quantity2 { get; set; }

        [EdiCondition("153", Path = "QTY/0/1")]
        public int Quantity3{ get; set; }
    }
```

**Comment by HamiltonManalo** [comment]
Resolved this by migrating custom changes to interchange and following pricedetails/price formatting. Was able to remove 1 level of nesting within the object this way.

**Comment by cleftheris** [comment]
Hi @HamiltonManalo glad you managed to sort this out!
