### ISSUE TITLE
Support for the 834: Benefit Enrollment and Maintenance

### ISSUE THREAD

**Issue by michaelachrisco** [indice-co/EDI.Net#79]
It would be nice if there would be an 834 sample in the test/Models folder.

**Comment by cleftheris** [comment]
Hi @michaelachrisco and thank you for your interest. 

Unfortunately the time is limited but If you get something working you can add a test with your sample data and code and submit a pull request. 

This is the case with the other samples as well and that will help future integrators.

**Comment by michaelachrisco** [comment]
Sounds like a plan. Ill plan on building out the 834.

**Comment by michaelachrisco** [comment]
834 class has been created and works as intended for writing. Reading, on the other hand, seems to not be working. I may revisit at some later time.

**Comment by michaelachrisco** [comment]
I'm still getting issues with the reading structure. I can partially read and the write tests all pass. @cleftheris Would you an open PR with the changes (so we/the community can collaborate) or wait until I get it working on both reading and writing? It may take a while...

Either way, thanks for the library! Its been working out great!
