### ISSUE TITLE
Need help with VB.Net integration

### ISSUE THREAD

**Issue by EDINewbie** [indice-co/EDI.Net#81]
Hi,

Great work your team have been doing, I am trying to use indiceEDI in my VB.net project but struggling to convert it properly. What I have for now is as below:

```vbnet
        Dim grammar = EdiGrammar.NewTradacoms()
        Dim interchange = Nothing
        Dim stream = New StreamReader("C:\Users\Mustafa\Downloads\edi\ODF2A1850.edi")
        interchange = New EdiSerializer().Deserialize(stream, grammar)
```

Compiler is giving error for deserialize as below, I thought stream needed to be stream reader object. I must be mucking up something very trivial.. Any help would be appreciated.

Severity	Code	Description	Project	File	Line	Suppression State
Error	BC30311	Value of type 'StreamReader' cannot be converted to 'EdiReader'

**Comment by cleftheris** [comment]
Hi from the looks of your code you it seems you are using the wrong overload of deserialize method. The one you should be working with is the [generic one](https://stackoverflow.com/questions/2957651/calling-a-generic-function-in-vb-net-c-sharp) passing the type of your own `MyOwnInterchangeClass`.

First define the interchange root class. The following is part of an existing C# sample found [here](https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/Models/EdiFact01.cs) 
```vbnet
Public Class MyOwnInterchangeClass
    <EdiValue("X(4)", Mandatory := true, Path := "UNB/0")>
    Public Property SyntaxIdentifier As String

   <EdiValue("9(1)", Path := "UNB/0/1", Mandatory := true)>
    Public Property SyntaxVersion As Integer
    
    
    '... more properties here ...
    
    <EdiValue("9(1)", Path := "UNB/0/1", Mandatory := true)>
    Public Property SyntaxVersion As Quote
End Class
```

Something like the following to deserialize it:

```vbnet
Dim grammar = EdiGrammar.NewTradacoms()
Dim stream = New StreamReader("C:\Users\Mustafa\Downloads\edi\ODF2A1850.edi")
Dim interchange = New EdiSerializer().Deserialize(Of MyOwnInterchangeClass)(stream, grammar)
```
 
Hope this helps.
