### ISSUE TITLE
Multiple Conditions

### ISSUE THREAD

**Issue by mlucarelli** [indice-co/EDI.Net#83]
I am unsure how to chain EdiCondition statements together such that it maps to a property if both conditions are satisfied.

Example)
For a BAL segment, when BAL/0 = "M" & BAL/1 = "YB" map to TotalOutstandingBalance

```
[EdiCondition("M", Path = "BAL/0"), EdiCondition("YB", Path = "BAL/1")]
public EdiBalance TotalOutstandingBalance { get; set; }
```

The above code does not seem to work.
Is there a recommended way of accomplishing this?

**Comment by cleftheris** [comment]
Hi can you provide me with an edi file fragment and I will try to check this out.

**Comment by cleftheris** [comment]
I have pinpointed the line where this is determined (It has been a while). So here it is 
[Conditional check for property binding](https://github.com/indice-co/EDI.Net/blob/d51cc57339796dda888f266a5478bea9d2351353/src/indice.Edi/EdiSerializer.cs#L541).

```csharp
if (found) { 
    var property = candidates.SingleOrDefault(p => p.PathInfo.PathInternal == path && 
                                                   p.Conditions.Any(c => c.SatisfiedBy(value)));
    if (property != null)
        return property;
}
```

the snippet above shows that in the current implementation all conditions are checked but the property is bound in case `any` is satisfied. I could provide an additional flag on the condition attribute that tells the serializer that some conditions *must* be satisfied. 

I will come back with an update soon.

**Comment by mlucarelli** [comment]
Below is a snippet of the segments.
`
BAL*P*YB*6.66~
BAL*P*TP*5.55~
BAL*M*J9*4.44~
BAL*M*YB*3.33~
`

And I am referring to the document located below on page 24.
http://www3.dps.ny.gov/W/PSCWeb.nsf/96f0fec0b45a3c6485257688006a701a/b756beac4d08857785257ec4005753e6/$FILE/99391968.pdf/810SR_IG_v22_20150407.pdf

Let me know if you need more :)

**Comment by cleftheris** [comment]
@mlucarelli I have not yet made any changes to the lib since your code seems to be working for me.

Can you check my commit above that includes a sample model and file and see if this is what you were looking for?

```csharp
        [EdiMessage]
        public class Invoice {
            [EdiCondition("P", Path = "BAL/0"), EdiCondition("TP", Path = "BAL/1")]
            public Balance TotalPaymentsAndRefunds { get; set; }

            [EdiCondition("M", Path = "BAL/0"), EdiCondition("YB", Path = "BAL/1")]
            public Balance TotalOutstandingBalance { get; set; }
        }

        [EdiSegment]
        public class Balance
        {
            [EdiValue("9(9)", Path = "BAL/2", Description = "Decimal Number")]
            public decimal Value { get; set; }
        }
```

**Comment by mlucarelli** [comment]
Try adding
```
[EdiCondition("P", Path = "BAL/0"), EdiCondition("YB", Path = "BAL/1")]
public Balance PriorBalance { get; set; }
```
That should produce the error.

**Comment by adminnz** [comment]
This is a pretty important requirement as nearly every single Edifact message I deal with has segments repeated with multiple qualifiers.
For example:

```
UNB+UNOA:2+SEN:ZZ+REC:ZZ+180403:0916+INTREF00000001'
UNH+MESREF00000001+IFCSUM:D:96A:UN:CNS200'
BGM++CONNOTE+1'
DTM+137:1803310800:201'
FTX+ABK++A'
FTX+AAY++CS+AGG:5.6'
FTX+AAY++SM+Notes1:Notes2:Notes3'
FTX+AAY++SE+SEC:100:BKK'
FTX+BLT+++1:2:3:4:5'
RFF+AIA:PartyCode:Status'
DTM+539+1804040010:201'
RFF+AHI:CONTRACT1'
UNT+12+MESREF00000001'
UNZ+1+INTREF00000001'
```

The FTX segments have 2 qualifiers, the AAY and the CS/SM/SE

**Comment by cleftheris** [comment]
I decided to introduce the `EdiAnyAttribute` it is used like so.

```scharp
[EdiCondition("P", Path = "BAL/0")]
[EdiCondition("YB", Path = "BAL/1")]
[EdiAny]
public Balance PriorBalance { get; set; }
```
If put alongside multiple condition attributes it will change the behavior to the old one.
