### ISSUE TITLE
.NET Framework 4 compability

### ISSUE THREAD

**Issue by LaggAt** [indice-co/EDI.Net#86]
Hi,
can I use this (and how) in a .NET 4.0 application?
Kind regards, Florian.

**Comment by cleftheris** [comment]
Right now it supports `.Net 4.5` >=
If your requirement is strictly .Net 4.0 I will check to see what is the effort for it. It should not be very difficult since I already support netstandart 1.1

**Comment by LaggAt** [comment]
Hi, would be gread if we could use it in 4.0 directly. For now we found a workaround using it separated from our main product.

**Comment by LaggAt** [comment]
Wow, just saw you already did it - that's great news for us!
Thanks, that was quick.
