### ISSUE TITLE
AutoEndSegmentGroup

### ISSUE THREAD

**Issue by mlucarelli** [indice-co/EDI.Net#87]
AutoEndSegmentGroup flag does not appear to function properly for X12.
When it is set to true the normal methodology of detecting segments breaks and produces an error.

To test simply set the AutoEndSegmentGroup flag to true for any of your existing tests; it should break upon running.

This AutoEndSegmentGroup flag would be very helpful for detecting N1 segment group loops that contain N3, N4, and/or PER segments where sequence end can not be set because of optional segments that may or may not appear after an N1 loop (Might be ITD, might be PAM, might be IT1, etc...).

**Comment by cleftheris** [comment]
I hear you. The task is not trivial though so it will teke some time to find a slot of my time to dive in.

**Comment by mlucarelli** [comment]
Would it be easier to allow for multiple sequence ends to be declared?

**Comment by cleftheris** [comment]
@mlucarelli Yes I am thinking of a similar approach that might be easier to implement. Maybe supplying an `IncludedSegments` list property instead.

**Comment by mlucarelli** [comment]
Yeah. It looks like you can change it in two places and it should work. 
https://github.com/indice-co/EDI.Net/blob/master/src/indice.Edi/Serialization/EdiSegmentGroupAttribute.cs (add new list property)
and
https://github.com/indice-co/EDI.Net/blob/master/src/indice.Edi/EdiSerializer.cs (line 374 add list check)

**Comment by mlucarelli** [comment]
I'd contribute it myself but I can't get the project to open properly in VS pro 2015.

**Comment by cleftheris** [comment]
Don't worry I will do it, just have not found the time. If you want do try download the vs 2017 community edition. It works side by side with vs 2015 just fine and needs no license.

**Comment by mlucarelli** [comment]
Thank you.

**Comment by cleftheris** [comment]
@mlucarelli  I have released a new version with support for SegmentGroup members on the  attribute level. Starting from v1.5, in addition to start segment & escape segments you can define all segment names included in the sequence. 

Please give it a try and give me feedback.

**Comment by cleftheris** [comment]
In addition I am planning a minor release to see if I can also make the AutoEndSegmentGroups flag work.

**Comment by mlucarelli** [comment]
I'm going to start testing it out now.
Do you have an example of the way your update is intended to be used?

Thank you again for all the work you do for this package!

**Comment by mlucarelli** [comment]
Looks like it is working!

With the data annotation below, an N1 group and its sub segments are properly captured
`[EdiSegment, EdiSegmentGroup("N1", "N3", "N4", "PER")]`

**Comment by cleftheris** [comment]
I am very pleased It did!

Can you give me a sample model and test file so I can create a test and update documentation section on the README file?

Cheers!
