### ISSUE TITLE
Stack empty InvalidOp exception parsing X12

### ISSUE THREAD

**Issue by huwmanatee** [indice-co/EDI.Net#88]
I am experiencing an InvalidOperation exception with the text "Stack empty when attempting to parse an EDI 204 payload using X12 grammar.

Here is the Stack Trace in part:
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Stack`1.Peek()
   at indice.Edi.EdiSerializer.DeserializeInternal(EdiReader reader, Type objectType)
   at indice.Edi.EdiSerializer.Deserialize[T](TextReader reader, IEdiGrammar grammar)

Any ideas?

**Comment by sManx3** [comment]
I appear to be getting the same result trying to parse a [CMS 271 response file](https://www.cms.gov/Medicare/Coordination-of-Benefits-and-Recovery/Mandatory-Insurer-Reporting-For-Non-Group-Health-Plans/Archive/Downloads/NGHPInterfaceSpecVersion21.pdf).  

Attached are 2 example files and simple interchange I was trying to use.
[interchange.txt](https://github.com/indice-co/EDI.Net/files/1921033/interchange.txt)
[NYSample.txt](https://github.com/indice-co/EDI.Net/files/1921035/NYSample.txt)
[SFSample.txt](https://github.com/indice-co/EDI.Net/files/1921036/SFSample.txt)

**Comment by cleftheris** [comment]
@sManx3  Thanks for the feedback this is very helpful

**Comment by huwmanatee** [comment]
Please see my email for the payload.

**Comment by cleftheris** [comment]
I did check the commits to see when 1.1.2 came out and from the looks of it this broke when #31 was fixed.

The 1.1.2 release introduced the following changes https://github.com/indice-co/EDI.Net/commit/9668036117447b3409cf0676adcc2792a7a262cb
