### ISSUE TITLE
Missing build environment documentation

### ISSUE THREAD

**Issue by cwhellams** [indice-co/EDI.Net#9]
EDI.net appears to now be using .net Core (RC2) ? 

It would be useful to add some short notes on the development environment required in order to be able to work on and build the source e.g.

- Visual Studio version 
- External dependencies required e.g. .net Core
- Any other tools, libraries or NuGet packages expected

If you do not have .net core installed you will get a message such as this, which does not really tell you what the root cause of the problem is - luckily Google will yield the root cause !

 The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

reason : https://github.com/NuGet/Home/issues/2616

**Comment by cleftheris** [comment]
Hi @cwhellams, 

I agree and will address this soon. What I don't know yet is the minimum requirements for VS and nuget in order to run `dotnet core 1.0 RTM`. My guess would be VS 2012 but will have to check this out first.
