### ISSUE TITLE
Nested SegmentGroups With Same Starting Name

### ISSUE THREAD

**Issue by richardwalenga** [indice-co/EDI.Net#91]
I have to parse an X12 file format which uses the same segment name (TFS) for two purposes:
- to define a tax return
- to define schedules within the return

A simplified structure looks like this:

```code
ISA
GS
ST
    TFS~T2~900
        REF
        DTM
        TFS~T3~S03A01~PG~160~94~CE
            REF
        TFS~T3~S1~PG~161~94~J
            REF
SE
GE
IEA
```

This [commit](https://github.com/richardwalenga/EDI.Net/commit/c55196f8516665be462343d1dcb128e33e45069a) is how I propose to solve the issue.  I had to make this kind of adjustment to prevent the return from being popped off the stack.

The return class is defined like so:

```csharp
[EdiSegmentGroup("TFS", SequenceEnd = "SE", AllowNestedGroupWithSameStartSegment = true), EdiCondition("T2", Path = "TFS/0")] 
public class FuelTaxReturn
{
     public DateSegment DateSegment { get; set; }
     public ReferenceSegment Reference { get; set; }
     public List<TaxSchedule> TaxSchedules { get; set; }
}

The declaration of the schedule starts with
[EdiSegmentGroup("TFS"), EdiCondition("T3", Path = "TFS/0")] 
public class TaxSchedule
{
   public ReferenceSegment Reference { get; set; }
}
```

There is a bit more to these classes in my real code but I think this adequately describes my situation.  Any thoughts?

**Comment by cleftheris** [comment]
This seams reasonable, although I recently made some changes to the code you are referring to. I will check if I can make a failing test with this.

**Comment by richardwalenga** [comment]
FYI, I discovered in further testing my modification doesn't handle more than one return in the same file properly.

```
TFS~T2~CCR  
  TFS~T3   
  TFS~T3  
TFS~T2~SDR  
  TFS~T3  
  TFS~T3
```
When the second return is reached, two items need to be popped off the stack and only one is getting popped off.  The logic surrounding my new boolean property will need to change.  I think the answer is to move the break inside closeThisLevel like so:

```
  if (closeThisLevel) {
    level.Close();
    index = level.Index + 1;
    break;
  }
```

**Comment by dresscodeclothing** [comment]
Seconding this issue...

**Comment by richardwalenga** [comment]
This was tricky to resolve but I believe this [second commit](https://github.com/richardwalenga/EDI.Net/commit/ee4cd3b47bb8d22428178c3dee46e209ce14b16b) I made to my branch gets the job done.  It introduces more complexity than I had hoped would be necessary but I don't think it is excessive.  Am I making this harder than it ought to be?

If you are satisfied with the direction I am taking, I can turn this into a pull request.

**Comment by mlucarelli** [comment]
Why not use multiple condition data annotations instead?

Example for EDI 810 with multiple uses for BAL segment with P as the first value.
```
BAL*P*YB*6.66~
BAL*P*TP*5.55~
```

```
[EdiCondition("P", Path = "BAL/0"), EdiCondition("YB", Path = "BAL/1")]
public EdiBalance PriorBalance { get; set; }

[EdiCondition("P", Path = "BAL/0"), EdiCondition("TP", Path = "BAL/1")]
public EdiBalance TotalPaymentsAndRefunds { get; set; }
```

**Comment by richardwalenga** [comment]
@cleftheris let me know if there is anything you need from me.

**Comment by richardwalenga** [comment]
@cleftheris I added a [new commit](https://github.com/richardwalenga/EDI.Net/commit/7627da11abc49a036508d010e70bca782a12e0ae) to my feature branch which makes a slightly altered version of your test pass.  I added some comments to your commit explaining what I had to change and why.

**Comment by cleftheris** [comment]
@richardwalenga Please proceed and make a pull request. Before you do so, you will have to fork the repo again or pull the latest changes. The only thing I am not comfortable with, is I believe the extra setting `AllowNestedGroupWithSameStartSegment ` on the Attribute. I think it will introduce some confusion and I am already struggling to make some of the Library features more intuitive. That said can we live without this? Furthermore the mare existence of a Condition attribute is a good indicator that there might be a chance of nesting. Thanks for taking the time to give back.

**Comment by richardwalenga** [comment]
@cleftheris I can understand your reservations about AllowNestedGroupWithSameStartSegment.  I did consider instead checking for the presence of at least one EdiCondition on the level in place of that attribute, but that in itself wouldn't be enough information to know this current segment group could be a child of the existing segment group, a sibling of its parent, etc.

I am thinking with the way things are currently structured, the only way viable way to accommodate this need without a new EdiSegmentGroup attribute is to have new instances of EdiStructure get a reference to the parent EdiStructure passed in via the constructor at the end of EdiSerializer's TryCreateContainer like so:

```csharp
stack.Push(new EdiStructure(newContainer, propValue, index, current));
```

The EdiStructure class would have to be changed to include this new field and constructors:
```csharp
private readonly EdiStructure _Parent;

public EdiStructure(EdiStructureType container, object instance)
        : this(container, instance, 0, null) {

public EdiStructure(EdiStructureType container, object instance, int index, EdiStructure parent) {
       ValidationUtils.ArgumentNotNull(instance, "instance");
       _Container = container;
       _Instance = instance;
       _Index = index;
        _Descriptor = typeStore.Get(instance.GetType());
        _Parent = parent;
        _CachedReads = parent?.CachedReads ?? new Queue<EdiEntry>();
}
```
What do you think of that?  I am not sure the logic inside the main foreach loop which descends the stack will get much simpler but it would save on having to keep a reference to the child structure and the use of at least one boolean.

**Comment by cleftheris** [comment]
@richardwalenga in the end I had to pass the parent level reference since I had to check for a level siblings before moving deeper inside the hierarchy. I am pushing a release right now. I am always open to improvements so I would like to see aditional test scenarios.
