### ISSUE TITLE
ISA/15 always null

### ISSUE THREAD

**Issue by AliakseiFutryn** [indice-co/EDI.Net#92]
Hi guys, I've tried to parse ISA/15, but not suсcessfully.

EDI 943 ISA sample:
`ISA~00~          ~00~          ~ZZ~11ITPL         ~01~004919486US    ~180126~1102~<~00401~000000087~0~P~>|`

What i have in my code:
`[EdiValue("X(1)", Path = "ISA/15", Description = "I15 - Component Element Separator")]
public string ComponentElementSeparator { get; set; }`

All ISAs were parsed except ISA/15, Would you so kind and provide me with an advice or tip?

Best wishes,
Aliaksei Futryn
Software Engineer

**Comment by AliakseiFutryn** [comment]
Here I excpect that `ComponentElementSeparator` should contains ">", just a clarification.

**Comment by cleftheris** [comment]
Hi @AliakseiFutryn,

this is a known issue with X12. Please watch issue #19 for updates and discussion.

I will be closing this as duplicate.
