### ISSUE TITLE
Weird group behaviour (add elements out of EdiCondition) after update to 1.6.0

### ISSUE THREAD

**Issue by SylwesterZarebski** [indice-co/EDI.Net#98]
I have classes (excerpt):
```csharp
[EdiMessage]
public class MessageInvoice
{
    [EdiElement, EdiPath("RFF/0")]
    public class ReferenceDetail
    {
        [EdiValue("X(3)", Path = "RFF/0/0")]
        public string CodeQualifier { get; set; }

        [EdiValue("X(35)", Path = "RFF/0/1")]
        public string Identifier { get; set; }
    }

    [EdiSegment, EdiPath("NAD")]
    public class PartyNameAddress
    {
        [EdiValue("X(3)", Path = "NAD/0/0")]
        public string CodeQualifier { get; set; }

        [EdiValue("X(35)", Path = "NAD/1/0")]
        public string PartyIdentifier { get; set; }
    }

    [EdiSegmentGroup("NAD", "FII", "RFF", "CTA")]
    public class PartyDetail : PartyNameAddress
    {
        public List<ReferenceDetail> References { get; set; }
    }

    [EdiCondition("SU", Path = "NAD/0")]
    public PartyDetail Seller { get; set; }

    [EdiCondition("BY", Path = "NAD/0")]
    public PartyDetail Buyer { get; set; }
}
```
with data excerpt:
```
...
NAD+SU+5900001400005::9++'
RFF+VA:5242106963'
NAD+BY+5900001400006::9++'
FII+PB+68103019999000330004191216'
RFF+IT:2404191216'
RFF+VA:5260309174'
NAD+DP+5900014215801::9'
RFF+VA:5384723478'
CUX+2:PLN:4'
...
```
With version 1.5.0 i have `Message.Buyer.PartyIdentifier` == "_5900001400006_", and with 1.6.0 == "_5900014215801_" which is wrong. Also with 1.6.0 `Message.Buyer.References` has 3 elements with additional wrong `RFF+VA:5384723478` inside (should have 2 elements).

If above examples are not sufficient, i could send full class and client's file using private channel (RODO has made this :-().

**Comment by cleftheris** [comment]
The sample is fine no need for the whole thing. What I would very much appreciate if you could make a pull request that adds a failing test (sample file fragment and models above) Check this test as an example https://github.com/indice-co/EDI.Net/blob/7a641de0a606f86c22554b34cda2b05822f0bb07/test/indice.Edi.Tests/EdiTextReaderTests.cs#L761

Then I can work towards a solution and keep the test case for future regression.

**Comment by SylwesterZarebski** [comment]
Thanks, i'll try, but probably till next week i'll not have time to make all this.

**Comment by cleftheris** [comment]
@SylwesterZarebski I added a failing test in my latest commit. If you need to add some Assertions check it out here https://github.com/indice-co/EDI.Net/blob/c5271ac8d38967488d8328826744a011e0c07b81/test/indice.Edi.Tests/EdiTextReaderTests.cs#L782

**Comment by SylwesterZarebski** [comment]
Thanks, i've created pull request #100.
